- cli/daemon/dash/server.go
We've seen cases where net/http's content type detection
gets it wrong for the bundled javascript files.
Handle this by specifying the content type manually.
Fixes #22
> cli/daemon/dash: specify content type for javascript files

- cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
I see no reason why the example for float32 should be "2.3" while it should be "fl2.3" for float64 in the dashboard. If there is any reason, please feel free to discard this PR.
> cli/daemon/dash/dashapp: use "2.3" instead of "fl2.3" for float64

- cli/daemon/dash/dashapp/tsconfig.json
Using this is required as per [TypeScript docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). Having no `baseUrl` also broke intellisense in my editor (Webstorm).
> cli/daemon/dash/dashapp: add required `baseUrl` to tsconfig

- cli/internal/codegen/ts.go
- cli/internal/codegen/ts_test.go
GET requests don't support body. However, the generated typesciprt api client always includes a body. As a result, you get the error when trying to make a GET request using the generated client: 
```
Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
```
I solved it by using the fact that `JSON.stringify(undefined) === undefined`. This means that if `req` is undefined, the request won't have any body.
Encore does complain if there's no body on a POST request. However, this won't be a problem since all POST requests from the API client always include params as body.
I'm of course willing to change the solution if you feel like another approach would fit better.
> cli/internal/codegen(ts): don't include body for GET requests

- cli/cmd/encore/init_windows.go
Please refer https://github.com/encoredev/encore/issues/56 
Git bash:
Cmd:
Powershell:
> Set console mode for stdout and stderr in windows. Fixes #56

- parser/schema.go
- parser/schema_test.go
The JSON struct tag parsing included other options beyond just the name,
leading to bugs when including ",omitempty" and so on.
Fix this by using the Name field and not the Value() method.
Fixes #65
> parser: fix json tag parsing

- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/codegen_testmain.go
- compiler/internal/codegen/codegen_wrappers.go
- compiler/internal/codegen/testdata/TestCodeGenMain__empty.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
- compiler/internal/codegen/testdata/variants.txt
- compiler/runtime/beta/auth/auth.go
- compiler/runtime/runtime/config/config.go
- compiler/runtime/runtime/request.go
This adds auth.WithContext for overriding the auth information propagated in API calls.
Fixes #83
> compiler: support overriding auth data in API calls

- parser/est/est.go
- parser/parser.go
- parser/testdata/resource_sqldb_cross_service.txt
- parser/testdata/resource_sqldb_helper.txt
- parser/testdata/resource_sqldb_outside_ref.txt
- parser/testdata/resource_sqldb_outside_svc.txt
This clarifies some of the business rules for referencing database resources, notably around allowing to pass around variables of type `*sqldb.Database`.
> parser: improve parsing logic for named databases

- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__empty.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
- compiler/runtime/runtime/config/config.go
- compiler/runtime/runtime/request.go
Since we were using reflect.Type to track the auth data type
we inadvertently caused tests to import other packages.
Work around this by using the string representation instead.
> compiler: fix potential circular import in tests

- docs/tutorials/rest-api.md
If you type `git push encore` without having committed your files, you get an error that tells that there are no tests, but the actual issue is that there are no new go packages. It would be nice to get a better message, but to avoid getting there it would be good if was mentioned somewhere that you should do this extra step of committing the new files.
Anyway, that triggered me to write a test and extend the rest-api tutorial to include writing a test, commit files and then push to commit.
Hopefully, you view this as an improvement to the tutorial.
> Documentation: Add test and deploy to rest-api tutorial

- cli/daemon/sqldb/cluster.go
The local development database was provisioned with
a very conservative, default memory limit of 16MB.
Change this to 1GB to support larger databases and
more complex queries.
Thanks to @vilhelmmelkstam for the report!
> cli/daemon/sqldb: increase shared mem cap

- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/codegen_test.go
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/variants.txt
- compiler/wrappers.go
Add support for the few additional types that were overlooked in the
implementation of the type decoder for query strings.
> compiler/internal/codegen: support remaining types

- .github/workflows/go.yml
- cli/daemon/dash/dashapp/package-lock.json
- cli/daemon/db.go
- cli/daemon/run.go
- cli/daemon/sqldb/cluster.go
- cli/daemon/sqldb/manager.go
> cli/daemon: database improvements

- docs/develop/services-and-apis.md
- Adds a note regarding path naming conflicts
- Adds recommendations on how to avoid conflicts by prefixing path parameters
Closes #112
> docs: document path conflicts & how to avoid them

- cli/internal/codegen/client_test.go
- compiler/internal/codegen/type_resolver_go118_test.go
- compiler/internal/codegen/type_resolver_test.go
This commit uses Go build tags to disable two tests which now
rely on Go 1.18 generics which are causing test failures when we
test on Go 1.17 or below.
> Disable generic tests when not Go 1.18

- cli/internal/codegen/client_test.go
- compiler/internal/codegen/type_resolver_go118_test.go
This commit adds two missing `// +build` tags so we can build with older go versions still (1.16) which don't have `//go:build` support yet
> Add missing `// +build` tags

- cli/daemon/run/run.go
This commit fixes the base64 encoding of secrets between the daemon and
run command to both use `RawURLEncoding`. Previously the run command encoded
using `RawStdEncoding` which caused an issue when the secret contained certain control
characters.
> Fix BASE64 Secrets encoding

- cli/cmd/encore/db.go
The 'encore db shell' command takes a service name, but in practice
this is almost always the directory name so it's convenient to be able
to autocomplete the directory names directly.
However most shells autocomplete directories by adding a trailing '/'
which breaks our service name lookup. Handle this better by stripping
any trailing '/'. While we're at it provide a better autocompletion hint
by specifying that only directory names should be autocompleted.
Fixes #103
> cli/cmd/encore: improve 'encore db shell' autocompletion

- docs/develop/databases.md
- docs/docs.cue
- docs/how-to/connect-existing-db.md
- docs/how-to/share-db-between-services.md
Improve database documentation across the board:
- docs/develop: document how to handle migration errors
- docs/how-to/share-db-between-services: minor tweaks
- docs/how-to: document how to connect to external dbs
> docs: various improvements

- compiler/runtime/cron/cron.go
It's unused and was never fully implemented.
We still store documentation in the export metadata.
> compiler/runtime/cron: remove (cron.Job).Doc

- docs/deploy/custom-domains.md
This commit fixes a couple of small things on the custom domains documentation.
> docs: Fix documentation typos on Custom Domains

- cli/daemon/daemon.go
- cli/internal/platform/client.go
We weren't correctly propagating the method to the client.
> cli: fix client generation

- docs/deploy/own-cloud.md
This commit adds Azure to the list of cloud providers
and documents how to link Azure to an app as well as why
we require Owner level permissions rather than just Contributor
within the Azure subscription.
> Add Azure Documentation

- CONTRIBUTING.md
when following the instructions on a freshly checked out repository the compilation fails with
```bash
go build ./cli/cmd/encore
cli/daemon/dash/server.go:26:12: pattern dashapp/dist/*: no matching files found
```
since the `dashapp/dist` the command is trying to embedd isn't build yet and doesn't exist.
Running the dashapps build command creates the files and the compilation runs through
> CONTRIBUTING.md: Fix instructions for building from source

- compiler/build.go
It needs to be broken up into two separate arguments
for the go tool to understand it properly.
> compiler: fix static linking toggle

- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/expected_golang.go
- cli/internal/codegen/testdata/expected_typescript.ts
- cli/internal/codegen/testdata/input.go
For endpoints that only return an error we were still trying
to decode the response.
> cli/internal/codegen: fix Go client code generator

- runtime/storage/sqldb/sqldb.go
When using the stdlib integration the connection pool settings
must be configured separately.
Thanks @ValeriaVG for reporting!
> runtime/storage/sqldb: set max open conns for stdlib

- runtime/runtime/config/config.go
- runtime/storage/sqldb/sqldb.go
- runtime/storage/sqldb/sqldb_test.go
To support additional flexibility in how Encore works with Cloud Run
add the ability to customize whether Encore should use TLS certs
when connecting, as well as tweaking the connection pool sizes.
> runtime/storage/sqldb: support tls certs, max connection config

- runtime/runtime/config/config.go
- runtime/runtime/setup.go
- runtime/runtime/setup_cloud.go
- runtime/runtime/setup_local.go
- runtime/runtime/shutdown.go
- runtime/storage/sqldb/sqldb.go
Serverless environments such as Cloud Run that frequently scale up
and down can cause unclean PostgreSQL connection shutdowns.
The PostgreSQL server can take a long time (many minutes) to detect this
and release the connection slow. This can lead to out-of-connection
errors even when there are no active connections.
Fix this by handling SIGINT/SIGTERM signals and gracefully shutting down
when detected.
> runtime: add graceful shutdown support

- runtime/beta/errs/errs_internal.go
It's causing annoying build errors when using this module for
use cases outside of building an Encore app, such as referencing
the config structs.
Having this build tag is not important for now as the public API is
still in a separate module. If we go ahead with merging that into this
repo we can revisit this decision.
> runtime/beta/errs: remove encore_internal build tag

- cli/daemon/run/run.go
- cli/daemon/run/tests.go
- cli/daemon/runtime/config/config.go
- runtime/runtime/config/config.go
- runtime/storage/sqldb/sqldb.go
- runtime/storage/sqldb/sqldb_test.go
It's common to use the same database server with multiple databases.
In combination with client side TLS certificates this creates an
enormous amount of duplicated data, to the point where the size of the
encoded config can exceed the 64KiB limits imposed by Cloud Run.
Fix this by separating out the SQL Server configuration from the
SQL Database configuration, so that multiple databases on the same
server can use the same TLS configuration.
> runtime: separate sql server config from databases

- parser/schema.go
- parser/schema_test.go
Parse and store the struct field tags in the Field metadata proto. These fields will be used as hints to the compiler when generating marshalling code.
> parser/schema.go: Populate Tags and RawTags in the struct Field metadata

- parser/encoding/request.go
This commit adds a new `DescribeRPC` function to the encoding package.
This function's job is given an RPC to describe how to encode requests
and responses for that RPC on the wire.
The output of this function can then be used for both the client generation
and for the code generation inside Encore request handlers for applications.
> Add `encoding.DescribeRPC`

- internal/gocodegen/marshalling.go
- internal/gocodegen/package.go
This commit ports all the `typeDecoder` logic from compiler/internal/codegen/codegen_main.go
into a new shared package called `gocodegen` and adds a new set of methods for encoding to
strings for use in the Go client.
I've not removed or modified the existing compiler to use this new package yet. But that
will be a future commit once we've finished adding the header support to the compiler.
```go
type SvcAllInputTypes[A any] struct {
A    []time.Time `header:"X-Alice"`         // Specify this comes from a header field
B    int         `query:"Bob"`              // Specify this comes from a query string
C    bool        `json:"Charile,omitempty"` // This can come from anywhere, but if it comes from the payload in JSON it must be called Charile
Dave A           // This generic type …
```
> Shared Go Code Generator for Marshalling

- parser/encoding/rpc.go
This commit adds a new `DescribeResponse` function to the encoding package.
This function's job is to describe the http wire representation of a Response type
The output of this function can then be used for both the client generation
and for the code generation inside Encore request handlers for applications.
> Add encoding.DescribeResponse

- cli/internal/codegen/client_test.go
- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/README.md
- cli/internal/codegen/testdata/expected_golang.go
- cli/internal/codegen/testdata/expected_typescript.ts
- cli/internal/codegen/testdata/input.go
- cli/internal/codegen/utils.go
- pkg/golden/golden.go
This commit adds header support to the Go Client Generator using the new
DescribeRPC and shared Type Marshaling generator.
The golden package is now being used for the Client Generator to make it easier
to update the expected test files.
It updates the input to the client generator test to include a bunch of new
cases to try and expose as many test edges as possible.
> Add Header support to Go Client Generator

- internal/gocodegen/marshalling.go
The WriteToFile method also writes body and json helper methods which aren't added to the list of builtins
> internal/gocodegen/marshalling Write marshaller for body and json

- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- internal/gocodegen/marshalling.go
`any` can only be used in > go 1.18.
> internal/gocodegen/marshalling remove dependency on go 1.18

- parser/encoding/rpc.go
Adds a helper methods to describe how an auth struct should be marshalled
(branched off https://github.com/encoredev/encore/pull/230)
> parser/encoding/rpc: add auth param description

- cli/daemon/run/testdata/echo/test/endpoints.go
- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
- cli/daemon/run/testdata/echo_client/main.go
- cli/daemon/run/testdata/echo_client/main.ts
- cli/daemon/run/testdata/echo_client/package.json
- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/expected_golang.go
- cli/internal/codegen/testdata/expected_typescript.ts
- cli/internal/codegen/typescript.go
This commit adds support for query strings fields to be used in
requests made to raw endpoints.
> Generated Clients: Query Strings in Raw Endpoints

- cli/daemon/run/run_test.go
- cli/daemon/run/testdata/echo/echo/echo.go
- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
- cli/daemon/run/testdata/echo_client/main.go
- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__token_auth.golden
- compiler/internal/codegen/testdata/token_auth.txt
- compiler/internal/codegen/testdata/variants.txt
This commit adds support for using custom structs instead of the authorization token as input to the encore auth handler, e.g.
```
type AuthParams struct {
Header string `header:"X-Header"`
Query  string `query:"query"`
}
//encore:authhandler
func AuthHandler(ctx context.Context, params *AuthParams) (auth.UID, *AuthParams, error) {
return "user", params, nil
}
```
In this example, the request handler will attempt to parse the `Header` field from the request header and the
`Query` field from the request query string.
> compiler/internal/codegen: Add support for named struct auth params

- cli/daemon/run/testdata/echo/test/endpoints.go
- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
- cli/daemon/run/testdata/echo_client/main.go
- cli/daemon/run/testdata/echo_client/main.ts
- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/expected_golang.go
- cli/internal/codegen/testdata/expected_typescript.ts
- cli/internal/codegen/typescript.go
- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- runtime/runtime/setup.go
This commit adds URI encoding to path segments when called
from the generated clients. This allows for user input
to be passed directly to the client and through the URL segments
without worrying about segments not aligning.
This work showed a bug where Encore's routing layer was using
the already decoded path, which meant the path:
```
/account/abc%2Fdeposit_usd%2F%2F200
```
Was being routed as:
```
/account/abc/deposit_usd/200
```
This was fixed by using `req.URL.EscapedPath()` in the runtime
and then adding `UnescapePath` to the code which reads the path
segments and passes them to the running application
> Generated Clients: URI Encode Path Segments

- cli/daemon/run/run_test.go
- cli/daemon/run/testdata/echo/endtoend/endtoend.go
- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
This commit takes the tests we perform for the generated
clients and runs the same tests for the generated intra-service
wrappers as well.
> Add an end to end test for intra-service calls

- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/expected_golang.go
- cli/internal/codegen/testdata/expected_typescript.ts
- cli/internal/codegen/typescript.go
This commit changes the generated clients, so when a header
is not sent by the server, but is expected by the client - rather
than providing a default value, the client will instead raise an
error.
This aligns with the behaviour when JSON payloads are not able
to be unmarshalled into the correct types and provides a more
fail-safe behaviour on the clients.
> Generated Clients: Error on missing response headers

- cli/cmd/encore/app.go
- cli/daemon/dash/dash.go
- cli/daemon/dash/dashapp/package-lock.json
- cli/daemon/dash/dashapp/package.json
- cli/daemon/dash/dashapp/src/components/Nav.tsx
- cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
- cli/daemon/dash/dashapp/src/components/api/SchemaView.tsx
- cli/daemon/dash/dashapp/src/components/api/schema.ts
- cli/daemon/dash/dashapp/src/components/app/AppAPI.tsx
- cli/daemon/run/run.go
- cli/daemon/run/run_test.go
- cli/daemon/run/testdata/echo/echo/echo.go
- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
- cli/internal/appfile/appfile.go
- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/expected_typescript.ts
- cli/internal/codegen/testdata/input.go
- cli/internal/codegen/typescript.go
- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__empty.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- go.mod
- go.sum
- parser/encoding/rpc.go
- runtime/runtime/config/runtime.go
- runtime/runtime/request.go
This PR adds support in the local dashboard to support header fields and query fields, as well as the new authentication handler type which supports a parameters object rather than just a bearer token string.
Fixes #245
> Support in Local Dashboard for new Header Support & Auth Types

- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__only_query_auth.golden
- compiler/internal/codegen/testdata/only_header_auth.txt
- compiler/internal/codegen/testdata/only_query_auth.txt
Fix "unused variable" bug when having only headers or query parameter in auth data type.
> compiler/internal/codegen: Allow header only auth

- cli/cmd/encore/daemon/daemon.go
- cli/cmd/encore/daemon/schema.sql
- cli/daemon/apps/apps.go
- cli/daemon/daemon.go
- cli/daemon/dash/dash.go
- cli/daemon/dash/trace.go
- cli/daemon/db.go
- cli/daemon/engine/runtime.go
- cli/daemon/engine/trace/trace.go
- cli/daemon/internal/manifest/manifest.go
- cli/daemon/run.go
- cli/daemon/run/http.go
- cli/daemon/run/manager.go
- cli/daemon/run/run.go
- cli/daemon/run/run_test.go
- cli/daemon/run/testdata/echo/go.mod
- cli/daemon/run/tests.go
- cli/daemon/run/watch.go
- cli/daemon/sqldb/cluster.go
- cli/daemon/sqldb/docker/docker.go
- cli/daemon/sqldb/driver.go
- cli/daemon/sqldb/external/external.go
- cli/daemon/sqldb/manager.go
- cli/daemon/sqldb/proxy.go
- cli/daemon/sqldb/utils.go
- go.mod
- go.sum
To support dependency injection Encore needs to generate code that is
written into the app's file tree so that editors can pick it up.
It would be frustrating if the code generation was only enabled after
running 'encore run', but the daemon had no way of knowing the location
of Encore apps on the local filesystem.
Fix this by introducing a local sqlite db that tracks known Encore apps
on the local filesystem. We can then use this to watch the filesystem for
changes to the known Encore apps and trigger code generation even without
having to run 'encore run'.
> all: keep track of known apps persistently 

- cli/daemon/run/run_test.go
- cli/daemon/run/testdata/echo/echo/echo.go
- cli/daemon/run/testdata/echo_client/client.ts
- cli/daemon/run/testdata/echo_client/client/client.go
- cli/daemon/run/testdata/echo_client/main.go
- cli/daemon/run/testdata/echo_client/main.ts
- cli/internal/codegen/testdata/expected_golang.go
- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- internal/gocodegen/marshalling.go
This PR implements changes to only call the encore authhandler if at least one auth field is set. If an auth field is set, the authhandler will be called for *all* endpoints (including public ones). Unauthenticated errors will be ignored for all but 'auth' endpoints, whereas other errors (such as parsing error, other authhandler errors) will be returned to the caller.
> compiler/internal/codegen: Skip auth validation for empty auth params

- cli/cmd/encore/daemon/daemon.go
- cli/cmd/encore/main.go
- cli/daemon/pubsub/nsq.go
- cli/daemon/run.go
- cli/daemon/run/async.go
- cli/daemon/run/manager.go
- cli/daemon/run/resources.go
- cli/daemon/run/run.go
- cli/daemon/run/watch.go
- cli/daemon/sqldb/cluster.go
- compiler/build.go
- compiler/internal/codegen/codegen_main.go
- compiler/rewrite.go
- go.mod
- internal/optracker/optracker.go
- parser/meta.go
This commit refactors the resource service startup, such
that if you add code for a SQL database or pubsub topic when
`encore run` is already running, the watch will pick up those
changes and start the required services on your system.
This involved:
- Moving the resource startup code into a new `ResourceServices` struct
- Moving the `OpTracker` into it's own package from `cli/daemon/run` so it could be passed around
- Making `OpTracker` reciever functions work will `nil` pointers (i.e. no-op) so the calling code doesn't need to check
While refactoring this code, I added a `asyncBuildJobs` which allows jobs which can be run in paralel to be run in paralel.
I also added an NSQ log adapter and limited the logs to warning's and above.
This means the outputs from the daemon and CLI run now …
> Refactor resource service startup

- runtime/runtime/config/config.go
- runtime/runtime/cors/cors.go
- runtime/runtime/cors/cors_test.go
Add a way to specify extra headers that should be allowed through CORS.
> runtime/runtime/cors: support extra headers

- cli/cmd/encore/app.go
This fixes an issue where new apps did not actually have `encore.dev` as a dependency,
or had outdated versions if using a template.
> Run `go get encore.dev@latest` on app creation

- parser/feature_pubsub.go
- parser/meta.go
- parser/schema.go
- parser/schema_test.go
- parser/testdata/pubsub.txt
- parser/testdata/pubsub_err_attributes_not_start_encore.txt
This commit adds a compiler error for any attribute
names which start `encore` as we need to reserve them
so we can pass Encore specific meta data for PubSub
messages
> Reserve attribute names starting `encore`.

- runtime/pubsub/topic.go
- runtime/pubsub/types.go
interface{} caused a compilation error in GO 1.18.3
> runtime/pubsub: Change type of Subscription to struct

- cli/cmd/encore/daemon/daemon.go
Opening the database fails if the parent directory does not exist.
This can happen if trying to run `encore run` prior to logging in.
> Create config dir before opening db

- parser/parser.go
- parser/parser_resources_usage.go
Most requires are bound to package level varaibles, like this:
```go
var db = sqldb.Named("svc")
```
We track the identifier `db` as being bound to the database `svc`.
However, it's possible to make calls like this:
```go
var db = sqldb.Named("svc").Stdlib()
```
In this case `db` is not longer bound against the database `svc`, as
the named resource isn't directly bound.
The refactored resource parser, correctly identified the named database,
and it wasn't bound to a varaible in the package. However, older code
was written expecting an identified resource to always have an ident.
This is what caused the nil pointer panic. I've added checks for `nil`
identifiers, and skip the resource usage tracking if we know that resource
isn't bound against anything.
> Fixed nil pointer on unbound resources.

- cli/daemon/engine/trace/trace.go
- pkg/eerror/error.go
- pkg/eerror/stack.go
This commit adds a simple error package to track errors which
occur during trace reads.
> A `eerror` package for tracer to report errors with metadata

- runtime/runtime/test_interface.go
This commit fixes `sqldb` when tests are being executed.
A bug was introduced where the new test tracing created a
request associated with the Go routine, but did not tag it
with the name of the service which was under test.
> Fix sqldb under test.

- runtime/appruntime/api/reqtrack.go
- runtime/pubsub/subscription.go
In some circumstances the fact that we were running a test
was not being propagated to child requests.
> runtime/appruntime: fix test tracking

- runtime/pubsub/subscription.go
In some circumstances the pubsub subscriber would
not copy parent information over to the span.
> runtime/pubsub: fix tracing

- parser/schema.go
- parser/testdata/struct_duplicate_json_ignore.txt
Our parser tries to detect name collisions, but did not
consider the case where the field is ignored with `json:"-"`.
Handle this case. Thanks to @melkstam for the report.
Fixes #319
> parser: support multiple fields with JSON ignore

- CONTRIBUTING.md
- cli/daemon/dash/dashapp/babel.config.js
- cli/daemon/dash/dashapp/jest.config.js
- cli/daemon/dash/dashapp/jest.setup.js
- cli/daemon/dash/dashapp/package-lock.json
- cli/daemon/dash/dashapp/package.json
- cli/daemon/dash/dashapp/src/__tests__/Combobox.test.tsx
- cli/daemon/dash/dashapp/src/components/Combobox.tsx
- cli/daemon/dash/dashapp/src/index.d.ts
- cli/daemon/dash/dashapp/tsconfig.json
Adding `Jest` and `react-testing-library` as dependencies to the project (the recommended unit testing libs for React). Also needed to add some `babel` dependencies which allow us to use ES6 Modules, JSX, and TypeScript in our tests.
Really want to have some unit tests for the front-end. Not having anything is bad
We should run the FE unit tests during CI for pull requests. What do you think, should we add this to the existing GitHub action that we have or should we create a new one for testing & linting the front-end code?
> Add front-end unit test possibilities

- compiler/internal/codegen/api_handlers.go
- compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
If an API returns `(nil, nil)` we erroneously cloned this
response as `(&T{}, nil)`. Fix this.
> compiler/internal/codegen: clone nil as nil

- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/codegen_testmain.go
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
- compiler/internal/codegen/testdata/variants.txt
This commit ensures that all services get imported into
the generated `main.go` file for a built app.
This was to fix a bug where a service could be created using
a PubSub subscriber, but if a service only had subscribers and
had no API handlers, it was never imported by the main package,
thus never started up.
> Import all services into the main file

- cli/daemon/run/testdata/echo/di/di.go
- docs/develop/middleware.md
- parser/svc.go
We were using `resolveParameter` to find the receiver name.
This had the inadvertent effect of preventing use of
non-basic types inside the struct. Fix this by resolving
the receiver name by hand instead.
> parser: fix Service Struct parsing

- docs/docs.cue
- docs/how-to/entgo-orm.md
This is based on the discussion here: https://github.com/encoredev/encore/discussions/307, and my own usage of ent within my application. This is fairly early and there might be a better way of doing this with features of Encore I don't know yet.
It's very easy to integrate a heavy ORM like ent with Encore if you're okay with tinkering a bit with scripts and commands. This guide shows one way of doing it, which could be expanded, but this seems to work really well on my end. We could also add a section for using only Atlas if it could be useful.
Any feedback is very much appreciated!
> Add a how-to guide for using ent and atlas

- runtime/appruntime/api/handler.go
- runtime/appruntime/api/handler_test.go
If the API receives a request that cannot be decoded it
would sometimes cause a runtime panic. Fix this, and
improve test coverage of this area while we're at it.
Thanks @melkstam and Max D for the bug report
> runtime/appruntime/api: fix panic on request decode error

- compiler/internal/codegen/codegen_test.go
- compiler/internal/codegen/codegen_testmain.go
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
- compiler/test.go
- compiler/wrappers.go
- runtime/appruntime/app/app.go
- runtime/appruntime/config/config.go
This commit adds basic support for running tests from within
GoLand using the Encore GoLand Plugin (yet to be released).
GoLand runs tests in two phases; first it compiles the test, and
then it runs the compiled test file. It does this using the `-c`
argument to `go test`.
This causes problems for Encore as the current assumption is test
binaries will always execute through the Encore daemon, which isn't
the case here.
If we detect that `-c` has been passed to `encore test` then we need
to embed into the binary any enviromental varaibles that would normally
be passed from the daemon to the test (such as the secrets or runtime config).
This allows the Encore runtime to startup correctly for the tests when the execute.
A small change was also made to logging, such that when running in this …
> Support Unit Tests in GoLand

- cli/daemon/dash/dashapp/src/components/svgElements.tsx
For some reason the SVG did not render correctly
in Firefox. Adding an explicit background color
to the boxes fixes the issue.
> dashapp: fix flow rendering in Firefox

- .devcontainer/Dockerfile
- .devcontainer/scripts/install.sh
Also add support for arm64 while we're at it.
Fixes #367
> .devcontainer: upgrade to go 1.19

- cli/daemon/dash/dashapp/jest.setup.js
- cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx
- cli/daemon/dash/dashapp/src/components/trace/SpanDetails.test.tsx
Code highlighting for DB queries was made on the backend and that styling did not match what we did on the front-end. Now all code styling is done on the front-end with the same styling.
> Style database queries on the frontend

- cli/daemon/dash/dashapp/src/components/app/AppTraces.tsx
- cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx
* Add back the scrollbar to the tracing view (when the content is to big)
* Add "jump to logs" functionality (when you have logs)
* Add max height to the code parts of the tracing tooltips
If the request/response data is big then you have to scroll to get to the logs. Because we recently removed the scrollbar it became more cumbersome to get to the logs. 
**Jump to logs**
**Max height to code in tooltips**
> Add ability to scroll to logs in trace view

- runtime/appruntime/config/config.go
- runtime/storage/cache/manager_internal.go
For AWS's Redis TLS support we don't need a custom
cert, but still want to enable TLS. Add a config setting
that enables TLS even if there are no custom certs.
> runtime: add redis TLS override

- cli/cmd/encore/logs.go
`encore logs` doesn't print any message when started, so you can't tell whether it's waiting for logs. This PR adds the code to print a message to standard output when `encore logs` is started.
The message can be omitted by passing the `-q` flag to `encore logs`, which might be useful when using this command for scripting.
> Print message when encore logs is waiting for logs

- cli/cmd/encore/logs.go
Currently, `encore logs` returns an error when no environment is given. This PR makes `encore logs` default to the app primary environment.
> Default to primary environment when running encore logs

- cli/internal/conf/conf.go
We need to recreate the default token source and auth client to actually logout without restarting the daemon
> Reset clients on logout

- cli/cmd/encore/daemon.go
- cli/cmd/encore/daemon/daemon.go
- cli/internal/conf/conf.go
Marshal and handle authentication errors from the daemon's platform calls in a neater way
> cli/daemon: Add handling of auth errors

- compiler/internal/cuegen/testdata/basic_config_svc.cue
- compiler/internal/cuegen/testdata/basic_inline_struct_svc.cue
- compiler/internal/cuegen/testdata/basic_lists_svc.cue
- compiler/internal/cuegen/testdata/basic_maps_svc.cue
- compiler/internal/cuegen/testdata/basic_named_struct_multiple_uses_svc.cue
- compiler/internal/cuegen/testdata/basic_named_struct_single_use_svc.cue
- compiler/internal/cuegen/testdata/basic_with_cue_imports_svc.cue
- compiler/internal/cuegen/testdata/basic_wrappers_svc.cue
- compiler/internal/cuegen/testdata/cue_optional_tag_svc.cue
- compiler/internal/cuegen/testdata/cue_tags_svc.cue
- compiler/internal/cuegen/testdata/generic_named_types_svc.cue
- compiler/internal/cuegen/testdata/generic_top_level_type_svc.cue
- compiler/internal/cuegen/testdata/json_tags_svc.cue
- compiler/internal/cuegen/testdata/merge_identical_comments_svc.cue
- compiler/internal/cuegen/testdata/multiple_configs_in_service_svc.cue
- compiler/internal/cuegen/testdata/types_from_multiple_packages_svc.cue
- parser/feature_config.go
- parser/parser.go
- parser/svc.go
- parser/testdata/config_err_wrapper_used_in_wrapper.txt
- runtime/meta.go
This commit adds a new parser check to validate we don't have nested `config.Value[config.Value[T]]` types, as that could lead to unexpected behaviour.
Also fixes the test data for the `cuegen` as it hadn't been updated.
Finnaly I've re-introduced teh `EnvLocal` constant, but marked it as deprecated.
> [ENC-800] Error if `config.Value` types are nested

- parser/feature_config.go
- parser/parser_resources_usage.go
- parser/resources.go
- parser/testdata/config_err_use_from_other_service.txt
This commit adds a new check that prevents a configuration variable from being referenced from outside the service. This behaviour is needed as each service loads it's own unique configuration, and services will not be awaire of each others configurations at runtime.
Configuration passing can be achieved via API calls, rather than direct variable refernces.
> [ENC-832] Error if config is referenced outside the service

- cli/daemon/run/testdata/echo_client/client/client.go
- cli/daemon/run/testdata/echo_client/main.go
- cli/internal/codegen/golang.go
- cli/internal/codegen/testdata/expected_golang.go
- parser/feature_config.go
- parser/parser.go
- parser/schema.go
- parser/testdata/config_err_unexported_field.txt
If a data type has unexported fields and is used by a call to `config.Load[T]()` then we will now report an error to the user. This error is to prevent undefined behaviour when a user expects to be able to load an unexported field and is not able to.
This error will only occur on unexported fields used by config, unexported fields used by any other Encore feature will be unaffected.
> [ENC-799] Error on Unexported Config Fields

- cli/cmd/encore/check.go
- cli/cmd/encore/db.go
- cli/cmd/encore/eject.go
- cli/cmd/encore/main.go
- cli/cmd/encore/run.go
- cli/cmd/encore/test.go
This commit allows encore to obey the `-json` arg
which instructs the tests to output everything in
raw JSON. Currently we where always pretty printing the JSON output, which broke tooling intergration
(such as the GoLand plugin).
> Allow `encore test` to support `-json`.

- cli/daemon/daemon.go
Resolves #326. Adding a check for env_not_deployed error to display actionable error message.
> Actionable error message for client code gen

- parser/internal/names/resolver.go
- parser/parser.go
For Encore APIs defined as methods Encore generates
a user-facing `encore.gen.go` file that includes package-level
func wrappers for calling that API. That file is not intended
to be checked in to source control.
As a result we ended up with subtle bugs where the parsing
behavior depended on whether or not that file existed.
It existed during local development but not in CI/CD.
Fix this by ignoring that file during parsing to ensure consistent
behavior, and introduce a synthetic node in the name resolution
algorithm for method-based APIs to fix the underlying problem.
> parser: fix method API name resolution

- docs/how-to/entgo-orm.md
The documentation page had a few issues that were highlighted on Slack and while building a good example app, namely:
- The URL for installing ent changed, which send the reader on the wrong page and wasn't clear on how to install ent in an existing codebase.
- If setting up ent in a clean database, the database wouldn't exist, which would make the migrations fail. I added a section to clear this up.
- The review on the example app PR had a great suggestion to clean up the migration generation code. I've added it here too.
- There was a possible confusion where readers may try to use ent types as params or return types in Encore. That won't work, I added an example and a disclaimer.
This should make the docs a bit easier to follow and unblock any reader who tried to set it up in a new …
> Small improvements to the ent ORM documentation page

- docs/develop/client-generation.md
- docs/develop/errors.md
- docs/develop/metadata.md
- docs/develop/pubsub.md
Modified certain develop documentation pages with minor improvements meant to fix typos, grammatical mistakes, and add spaces between certain words which shouldn't be concatenated together.
> Modify develop documentation pages with improvements

- cli/cmd/encore/app.go
`encore clone` uses `origin` to keep track of the upstream repository. Instead, it should use `encore` for `git push encore` to work.
This PR adds a flag `--origin` to the `git clone` command (which is called by `encore clone`) to use the name `encore` to keep track of the upstream repository.
> Use 'encore' to keep track of the upstream repository

- .github/workflows/go.yml
- .github/workflows/release.yml
Github have deprecated Node.js 12 in their workers, so we needed to upgrade them to V3 to continue to have CI in this project.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/setup-go, actions/cache, actions/cache, actions/cache, actions/cache, actions/checkout
> Update Github Workflows due to deprecation

- compiler/build.go
- pkg/errinsrc/srcrender.go
This commit fixes an issue where for compiler errors, we where using the file which had been passed to the compiler. However due to `/*line :blah` directives inserted by Encore during the rewrite process, the rendered error lines did no align with the original source.
To fix it, we check if the file exists within the original app folder, if it does we rewrite the filename to that file, if it doesn't (i.e. it's an Encore generated file) we leave the filename as it was.
> [ENC-889] Use original files for compile errors

- pkg/errinsrc/srcrender.go
- pkg/errinsrc/testdata/Test_renderSrc_MultipleSeperateInSameFile__on_following_lines_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_MultipleSeperateInSameFile__on_following_lines_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_MultipleSeperateInSameFile__on_same_line_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_MultipleSeperateInSameFile__on_same_line_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_MultipleSeperateInSameFile__spaced_apart_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_MultipleSeperateInSameFile__spaced_apart_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_MutlilineError_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_MutlilineError_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__error_no_text_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__error_no_text_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__multiline_message_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__multiline_message_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__simple_error_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__simple_error_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__simple_help_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__simple_help_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__simple_warning_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__simple_warning_unicode.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__single_character_error_ascii.golden
- pkg/errinsrc/testdata/Test_renderSrc_Simple__single_character_error_unicode.golden
This commit adds a space into errors which make them detectable by GoLand as file links, and allows it to automatically make those links clickable.
> Made file paths in errors clickable

- parser/testdata/recursive_types.txt
- proto/encore/parser/schema/v1/walk.go
- proto/encore/parser/schema/v1/walk_test.go
For recursive and mutually recursive types we ended up
with a stack overflow from infinite recursion in the new
schema walker introduced in Encore v1.8.0.
Fix this by keeping track of which named types have
already been seen.
Fixes #438
> Handle walking of recursive types

- compiler/test.go
- pkg/errinsrc/errinsrc.go
- pkg/errinsrc/stack_dev.go
- pkg/errinsrc/stack_release.go
- runtime/config/config.go
This commit adds support to `encore test` for the new config system, and will pass the computed config into any tests, allowing them to opperate off those tests.
> Pass computed Config to Tests

- docs/community/index.md
I have fixed typos in [Community index page](https://encore.dev/docs/community). Take a look at the commits. Thanks.
> docs(index.md): Fix Typos in Community Index Page

- CONTRIBUTING.md
I have made this PR for 3 key reasons:
- Encore's Hacktoberfest
- Wording used "the" and could be replaced with encore
- Mistake with one link
> docs(CONTRIBUTING.md) update wording and fix mistake

- parser/est/est.go
- parser/est/selectors.go
- parser/feature_pubsub.go
- parser/internal/walker/cursor.go
- parser/meta.go
- parser/parser.go
- parser/parser_resources.go
- parser/parser_test.go
- parser/testdata/pubsub_err_attributes_not_start_encore.txt
- parser/testdata/pubsub_err_duplicate_subscription_names.txt
- parser/testdata/pubsub_err_subscriber_different_service.txt
- parser/testdata/pubsub_err_subscriber_not_function.txt
- parser/testdata/pubsub_err_subscription_func_not_in_service.txt
- parser/testdata/pubsub_err_subscription_name_invalid.txt
- parser/testdata/pubsub_err_topic_must_be_unique.txt
- parser/testdata/pubsub_err_topic_name_invalid.txt
- parser/testdata/pubsub_publish_in_middleware.txt
- parser/util.go
- pkg/errinsrc/internal/golocation.go
- pkg/errinsrc/srcerrors/errors.go
- pkg/errinsrc/srcerrors/helpers.go
- pkg/errinsrc/srcerrors/helptext.go
- pkg/errinsrc/utils.go
- pkg/idents/identifiers.go
- pkg/idents/identifiers_test.go
- runtime/appruntime/api/handler.go
- runtime/middleware/middleware.go
This commit modifies Pubsub such that you can now publish
to pubsub topics from global middleware. To do this we track
if the publish is within a service _or_ if it is directly called
by middleware, if it's called by middleware we then track
which middleware is doing the call, and what that middleware
is targeting.
When we convert the EST into metadata, we expand the middleware
targets out into the services which have the middleware installed.
I've also moved all pubsub errors over to the new error format
> [ENC-931] Allow middleware to publish to pubsub

- compiler/internal/codegen/codegen_config_marshalers.go
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/variants.txt
- compiler/rewrite.go
- e2e-tests/testdata/echo/echo/config.go
- parser/est/est.go
This commit fixes an issue where if a pointer type was used directly like `config.Load[*T]` the generated code would be to unmarshal a pointer, and would then cause a Go compile error.
> [ENC-957] Fix compile errors with Config pointers

- cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
We used to render it as 'curl -X * ...' which is not
valid syntax.
> dashapp: fix 'copy as curl' for raw endpoints

- cli/daemon/sqldb/cluster.go
- cli/daemon/sqldb/proxy.go
We've observed ~200ms connection establishment
times when using Encore's postgres proxy.
Profiling showed it came from calling docker
to get the container's port. Introduce a cache
that stores the most recently observed value
and periodically refetch it, instead of checking
it every time a connection is established.
This reduces the connection time from 200ms
to 35ms on my machine.
> cli/daemon/sqldb: cache cluster status

- compiler/build.go
- compiler/test.go
This is necessary for static linking of some libraries
like sqlite.
> compiler: set linkmode external for static linking

- compiler/build.go
- compiler/test.go
External linking only makes sense with cgo,
this was an unintended interaction.
> compiler: only use external linking with cgo

- compiler/internal/codegen/api_handlers.go
- compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- runtime/appruntime/api/handler.go
- runtime/appruntime/api/reqtrack.go
- runtime/appruntime/api/server.go
- runtime/appruntime/model/request.go
- runtime/request.go
This rewrites the paths we feed to `httprouter` in order to enable
different paths to use different parameter names in the same position.
This is not allowed by httprouter because it allows looking up parameters
by name, but we only use the positional indices so we don't need this
functionality. As a result we can just rewrite the paths to work within
the limits of httprouter and get the best of both worlds.
> codegen: unify path param names

- cli/daemon/apps/apps.go
When we generate user-facing code for all tracked apps during
daemon startup we were doing so while holding the query cursor
open, causing issues with table locks preventing things like `encore run`
from running concurrently. Fix this by scanning the table once into a slice,
and then iterating over it without holding the database cursor open.
> cli/daemon/apps: fix app table lock

- compiler/internal/codegen/middleware.go
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
- runtime/appruntime/api/handler.go
- runtime/appruntime/api/reqtrack.go
- runtime/middleware/middleware.go
This commit changes middleware to always return an HTTP status code in the middleware response.
> [ENC-966] Always report HTTP Status in Middleware

- cli/daemon/dash/dashapp/src/components/app/AppTraces.tsx
- cli/daemon/engine/trace/trace.go
The memory usage on the backend is manageable
but the browser does not handle displaying a large
amount of traces due to DOM and memory overhead.
> cli: limit trace storage to last 100 traces

- e2e-tests/testdata/echo/echo/echo.go
- parser/parser.go
- pkg/errlist/errlist.go
This commit removes the code which caused the parser to "sort" orders. While this seems like it made sense, the issue is the order in which the parser encounters errors is important as the first error can cause an inconsistent state within the parser, which results in more errors being detected and reported.
This was evident in the usecase where you had an API being referenced by a pubsub subscriber. If you caused the API to have some parser failure; such as an invalid signature, the PubSub subscriber would then report that you can't reference the API in that way.
The problem was in some examples, the PubSub error would be sorted first, resulting in the user thinking that PubSub can't access an API directly - where in reality they just had an issue with the way one of the API's was …
> [ENC-804] Remove sorting of Parser errors

- cli/cmd/encore/daemon/daemon.go
This changes the daemon to use the same tcp ports
every time, enabling better UX around connecting
to these ports for things like dev dashboard and
database proxies.
> cli: use deterministic tcp ports

- parser/meta.go
This is to allow the use of tools like Atlas, which create
atlas.sum files in the migration folder.
> parser: ignore non-sql files in migration dir

- e2e-tests/testdata/echo/go.mod
- pkg/ansi/ansi.go
It turns out the terminal escape codes we used were not
supported by all terminals, notably macOS's Terminal.app.
Fix this by using a different terminal escape code that does work.
> pkg/ansi: fix cursor save/restore

- cli/cmd/encore/logs.go
We were trying to be too smart in our logs keepalive,
when it turns out the server is already sending pings
and all that's needed is letting the websocket library
handle those with its default configuration.
> cli/cmd/encore/logs: fix keepalive

- e2e-tests/testdata/testscript/et_override_user.txt
- e2e-tests/testdata/testscript/et_override_user_authdata.txt
- runtime/et/auth.go
- tools/publicapigen/main.go
The release hasn't gone out yet, so let's do it while we can.
> runtime/et: rename new func to UpdateAuthInfo

- cli/daemon/run/run.go
- cli/daemon/run/tests.go
- cli/daemon/secret/secret.go
- e2e-tests/app_test.go
- e2e-tests/testdata/testscript/experiment_local_secrets_override.txtar
- internal/experiments/experiment.go
This adds an Encore experiment named `local-secrets-override`
that enables the ability to define a `.secrets.local.cue` file that
specifies local values for secrets to use instead of the ones stored
for the app as a whole.
> Add experiment to support overriding secrets locally

- compiler/wrappers.go
The go compiler uses the presence of `_test.go` files
as a signal to compile the test binary for a package.
Encore unconditionally generated such a file, which
meant that all packages would be compiled even if
they contained no actual tests. Fix this by only generating
such a file if the package contains other test files.
> compiler: skip generating test code if no tests exist

- cli/daemon/engine/trace/parse_test.go
- cli/daemon/engine/trace/trace.go
Trace version 9 emits the error message twice.
Handle this on the parser. We'll fix the duplication
in the next trace version.
> cli/daemon/engine/trace: fix error handling

- cli/cmd/encore/gen.go
- internal/clientgen/client.go
- internal/clientgen/javascript.go
When I was investigating to make sure the JavaScript client was the same as the TYpeScript client, I noticed that the JS PR was merged before the JS client generation was properly disabled. According to the comment on my initial PR, I've created this follow up to make sure it's disabled if it's deemed necessary.
> Disable JavaScript client generation for now

- runtime/appruntime/api/handler.go
- runtime/appruntime/api/handler_test.go
net/http's content type detection is not very
accurate, particularly for small payloads.
Set the content type explicitly.
Thanks Alex Guerrieri for the report.
> runtime: explicitly set content type

- cli/daemon/engine/trace/trace.go
- runtime/appruntime/api/handler.go
- runtime/appruntime/app/app.go
- runtime/appruntime/model/request.go
- runtime/appruntime/trace/events.go
- runtime/appruntime/trace/trace.go
- runtime/pubsub/manager_internal.go
- runtime/pubsub/subscription.go
This fixes some minor bugs related to how payloads
were represented in traces. PubSub message payloads,
in particular, were not being passed to the request
object which meant they were not being rendered.
> runtime: fix payload tracing

- cli/daemon/run/exec_script.go
- compiler/build.go
- compiler/exec_script.go
We were incorrectly using the working dir where
we should be using the script rel path.
Also propagate the op tracker for better visibility
into what the command is doing during compilation.
> compiler: fix exec script from other dir

- runtime/appruntime/app/app.go
- runtime/appruntime/app/appinit/appinit.go
- runtime/appruntime/app/setup_cloud.go
- runtime/appruntime/app/setup_local.go
GCP's Cloud Logging expects a different format
for level and timestamp field names. Handle this
by reconfiguring zerolog based on the runtime config.
Thanks Patryk Siemiński for the report!
> runtime: fix log format in GCP

- cli/cmd/encore/daemon/daemon.go
- cli/daemon/apps/apps.go
- cli/daemon/run/watch.go
- cli/daemon/watch.go
- go.mod
- go.sum
- pkg/watcher/event.go
- pkg/watcher/watcher.go
The existing library we where using had not been updated in a couple of years and uses a deprecated API on MacOS. This commit moves Encore over to using [fsnotify](https://github.com/fsnotify/fsnotify) as the core of the file system watching component.
> Move to FSNotify for file system watching

- cli/cmd/encore/daemon/daemon.go
- parser/dirs.go
- pkg/eerror/error.go
- pkg/eerror/zerolog.go
- pkg/errinsrc/errinsrc.go
- pkg/watcher/rlimit_nix.go
- pkg/watcher/rlimit_noop.go
- pkg/watcher/util.go
- pkg/watcher/watcher.go
The new FSnotify library we introduced in v1.10.5 had a bug where it would recursively recursive and watch the file system (i.e. we expontentaionally watch the file system).
This resulted in two side effects:
- Our attempt to ignore `node_modules` got bypassed, so we ended up watching everything inside node_modules
- We spent a lot of time going over the same folders again and again
This has been fixed by moving the main logic into the `WalkDir` call within the watch library.
Then we've modified the `walkDir` in the parser to also ignore the same set of folders, so we walk the app as quickly as possible.
This commit also updates the `eerror` package and intergrates it better with zerolog, so if an error with a stack trace  or an error with meta data is logged, we will extract them and add …
> [ENC-1072] Fix over watching of the filesystem

- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__empty.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- parser/est/est.go
- runtime/appruntime/api/server.go
- runtime/appruntime/config/config.go
- runtime/appruntime/cors/cors.go
- runtime/appruntime/cors/cors_test.go
This commit automatically adds any headers used within data types used within the Encore application to be added to the list of accepted headers used by the CORS middleware within the Encore runtime.
> [ENC-1073] Automatically add headers used in types to CORS config

- runtime/storage/sqldb/errors.go
- runtime/storage/sqldb/errors_test.go
- runtime/storage/sqldb/sqldb.go
- runtime/storage/sqldb/sqlerr/sqlerr.go
This adds a `*sqldb.Error` type which exposes information about the underlying database error. It also adds the new `encore.dev/storage/sqldb/sqlerr` package with common error codes that can be tested against in a database-agnostic way.
The error also contains the `DatabaseCode` field that provides a non-portable way of getting the precise error from the underlying database server.
> storage/sqldb: add sqldb.Error

- pkg/pgproxy/pgproxy.go
If the client requested SSL but the server does not support
SSL we reject the SSL request. However, instead of reading
a new startup message we would incorrectly proceed to
actually doing the SSL handshake.
Thanks Cilla for the report.
> pkg/pgproxy: fix ssl negotiation

- runtime/rlog/pkgfn.go
- runtime/rlog/rlog.go
We were only adding those fields to the zerolog.Event,
not to the trace.
> rlog: trace log fields from `With`

- runtime/appruntime/config/config.go
- runtime/appruntime/metrics/encore_cloud_exporter.go
- runtime/appruntime/metrics/gcp/cloud_monitoring.go
- runtime/appruntime/metrics/gcp_cloud_monitoring_exporter.go
The platform prefixes an Encore app metrics with their resource ID. To be able to export metrics to Encore Cloud, the runtime needs to know what the metric names in Encore Cloud are: these are injected into the runtime config by the platform, so that the runtime can use them to export metrics to Encore Cloud.
> Implement Encore Cloud metrics exporter

- cli/daemon/apps/apps.go
- internal/goldfish/goldfish.go
Use a short-term cache for caching the platform id for an app.
Fixes #554
> cli/daemon/apps: cache platform id only briefly

- cli/cmd/encore/daemon.go
- internal/version/version.go
When running outside of the GA channel, the daemon would not be restarted if you changed release channel or upgraded your nightly or dev build.
> Fix deamon restart

- pkg/idents/identifiers.go
- pkg/idents/identifiers_test.go
If new parts started with digits, they would be truncated, e.g.
`encore-123abc` -> `["encore","abc"]`
> ENC-1166 - Fix idents part parsing

- docs/observability/logging.md
It just bothered me that the rlog.Warn was not part of the logging.md text.
> refactor: add Warn to logging.md

- runtime/appruntime/api/handler_test.go
- runtime/appruntime/api/reqtrack.go
- runtime/appruntime/api/server.go
- runtime/appruntime/api/util.go
- runtime/appruntime/app/app.go
- runtime/appruntime/metrics/metrics.go
- runtime/metrics/metrics.go
- runtime/metrics/registry_internal.go
We defined `e_requests_total` as a logs-based metric, but considered the quota limitations of logs-based metrics, we've decided to treat default metrics like `e_requests_total` as custom metrics.
Custom metrics, as opposed to logs-based metrics, have higher quotas in GCP. This makes it easier to use them in Encore Cloud.
> Define default metric e_requests_total as custom metric

- compiler/internal/codegen/api_handlers.go
- compiler/internal/codegen/auth_handler.go
- compiler/internal/codegen/codegen_main.go
- compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
- runtime/appruntime/api/auth.go
- runtime/appruntime/api/handler.go
- runtime/appruntime/api/reqtrack.go
- runtime/appruntime/model/request.go
The metrics code reads service numbers from the request tracker, which in turn reads them from API handler descriptors.
This PR modifies the code generator to add service numbers to API handler descriptors.
> Add service number to API handler descriptor

- pkg/scrub/scanner.go
- pkg/scrub/scanner_test.go
- pkg/scrub/scrub_test.go
The scanner mishandled double-quoted strings.
> pkg/scrub: handle quoted strings properly

- runtime/appruntime/metrics/gcp/cloud_monitoring.go
If no metrics have been collected, we shouldn't make any request to GCP. If we do, we get an error saying that the time series field can't be empty.
> Fix missing time series error

- .github/workflows/go.yml
- .github/workflows/release.yml
We've gotten reports that ubuntu-latest causes issues with glibc versioning
on older operating systems (including ubuntu 20.04).
Fix this by reverting to using an ubuntu-20.04 builder instead.
> .github: use ubuntu-20.04 builder

- CONTRIBUTING.md
When building from source, the `git-remote-encore` pluging needs to be manually installed to be able to clone projects (`encore app clone`).
> docs: Update documentation to build from source

- cli/daemon/dash/dash.go
- cli/daemon/dash/dashapp/package-lock.json
- cli/daemon/dash/dashapp/package.json
- cli/daemon/dash/dashapp/src/app.css
- cli/daemon/dash/dashapp/src/components/api/RPCCaller.test.tsx
- cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
- cli/daemon/dash/dashapp/src/components/api/SchemaView.tsx
- cli/daemon/dash/dashapp/src/components/api/api.ts
- cli/daemon/dash/dashapp/src/components/app/AppAPI.tsx
- cli/daemon/dash/dashapp/src/components/app/AppCaller.tsx
- cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx
- cli/daemon/dash/dashapp/src/lib/client/client.ts
- compiler/internal/codegen/api_handlers.go
- internal/clientgen/golang.go
- internal/clientgen/javascript.go
- internal/clientgen/typescript.go
- parser/encoding/rpc.go
Main change: 
* Request input (headers, query string and body) are now in the format in which the user would interact with the endpoint and not the GO request struct.
**Before**
**New**
Notice also that we are now showing the URL even when it does not have dynamic path params
Other changes:
* Always show the request path even when the path does not have dynamic parts (see screenshot above)
* Show the request url in the tracing view
* Replace the JSON viewer to the same lib that we use on app.encore.dev
**Old JSON viewer**
**New JSON viewer**
> Change API Explorer to use JSON field names and JSON output

- runtime/appruntime/metrics/encore_cloud_exporter.go
- runtime/appruntime/metrics/gcp_cloud_monitoring_exporter.go
This PR fixes a bug where multiple Cloud Run instances write to the same cumulative metric with different start times. By adding the Cloud Run instance ID to `node_id`, we avoid writing to the same time series which should fix the bug.
> Add Cloud Run instance ID to node_id

- runtime/appruntime/metrics/gcp/cloud_monitoring.go
- runtime/metrics/metrics.go
- runtime/metrics/registry_internal.go
We currently don't keep track of which services have emitted metrics for metrics defined outside services.
This PR adds a `valid` slice to time series to keep track of which services have emitted metrics.
> Keep track of which services have emitted metrics

- runtime/appruntime/metrics/gcp/cloud_monitoring.go
- runtime/appruntime/metrics/gcp/cloud_monitoring_test.go
- runtime/metrics/metrics.go
Currently, metrics defined within a service are exported even if they haven't been set by application code. This behavior leads to potentially confusing graphs when visualizing gauges.
> Export metrics only if set

- runtime/appruntime/config/config.go
- runtime/appruntime/config/parse.go
The runtime configuration on GCP is kept in a GCP secret manager secret to protect runtime secrets. We can avoid updating this secret unnecessarily by extracting the deploy_id as an env variable.
> ENC-1259: Make Runtime.DeployID overridable by ENV var

- cli/daemon/exec_script.go
- cli/daemon/run.go
- cli/daemon/run/exec_script.go
- cli/daemon/run/run.go
- cli/daemon/run/tests.go
- cli/daemon/secret/secret.go
- cli/daemon/sqldb/db.go
- cli/daemon/test.go
- e2e-tests/app_test.go
- runtime/appruntime/app/app.go
- runtime/appruntime/app/appinit/appinit.go
This improves the user experience of using secrets in a few ways:
* Downgrades missing secrets in local dev to a warning instead of a fatal error
* Fixes the secret caching when setting a secret and immediately restarting `encore run`
It also fixes a small miscellaneous bug with sqldb role granting.
> Secret handling tweaks

- runtime/appruntime/api/server.go
- runtime/appruntime/api/server_test.go
This adds trailing-slash-redirect handling to
make using Encore APIs slightly more forgiving.
It particularly makes frontend support better
since frontends otherwise require a trailing slash
for the root node.
> runtime: implement trailing slash redirect

- cli/cmd/encore/app/create.go
- cli/daemon/dash/dashapp/src/components/FlowDiagram/FlowDiagram.tsx
This adds support for defining examples with
placeholder values that are replaced on app
creation.
> Rewrite placeholders when creating app

- cli/cmd/encore/app/create.go
- cli/daemon/secret/secret.go
- cli/internal/platform/api.go
To improve the onboarding experience when
creating a new example app, support parsing
an `example.json` file in the newly created app
if it exists. Use that to set initial secrets on the
platform.
> Support example.json to set initial secrets

- compiler/internal/codegen/codegen_config_marshalers.go
- compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
This commit fixes a bug, where if a config file had additional config fields which where not needed by a config struct, it would cause the config unmarshal to exit early and miss the remaining fields
> Fix bug where additional config fields caused others to be missed

- cli/daemon/dash/dashapp/src/App.tsx
- cli/daemon/dash/dashapp/src/components/Nav.tsx
- cli/daemon/dash/dashapp/src/components/snippets/Code.tsx
- cli/daemon/dash/dashapp/src/components/snippets/snippetData.tsx
- cli/daemon/dash/dashapp/src/pages/SnippetPage.tsx
- cli/daemon/dash/dashapp/tailwind.config.js
* Make the inline code blocks look like in the encore.dev/docs
* Fix nav bar active styling by adding a unique path name to the index page (API explorer)
* Encourage users to suggest new snippets by adding a link to slack   
* Add hover styling to menu items
> Tweaks to snippet page in local dev dash

- docs/docs.cue
- docs/how-to/cgo.md
- pkg/appfile/appfile.go
We've had this as a server-enabled setting for some time,
but it's time to open it up and track it in the `encore.app` file.
> Add setting for enabling cgo in `encore.app`

- cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
- cli/daemon/dash/dashapp/src/components/api/api.ts
- cli/daemon/dash/dashapp/src/components/snippets/snippetData.tsx
The TypeScript code did not properly handle that the authorization encoding could be null.
Thanks Paul Smith for the bug report.
> dashapp: fix 'copy as curl' without auth handler

- cli/cmd/encore/run.go
- cli/daemon/run.go
We were defaulting to `localhost:4000` as the
listen address, which defaults to only listening
on tcpv4. Change to listening on all interfaces
by default by changing to `:4000`.
The default behavior can be overridden
with `encore run --listen=<addr>`.
Thanks Will Demaine for the report.
> Listen on all interfaces by default

- cli/daemon/dash/dashapp/src/components/app/AppTraces.tsx
- cli/daemon/dash/dashapp/src/components/icons.tsx
- cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx
Copying over what is now live on app.encore.dev so that you can view trace logs as JSON and expand/collapse fields.
Also:
* Remove "view stack trace"-buttons as that functionality is not working at the moment (we will look into that)
* Fix flying link bug (https://encoredev.slack.com/archives/CQFNUESN9/p1675696000355489)
> Show trace logs as JSON 

- cli/daemon/dash/dashapp/package-lock.json
- cli/daemon/dash/dashapp/package.json
- cli/daemon/dash/dashapp/src/App.tsx
- cli/daemon/dash/dashapp/src/components/Nav.tsx
- cli/daemon/dash/dashapp/src/lib/client/base.ts
- cli/daemon/dash/dashapp/src/lib/client/jsonrpc.ts
- cli/daemon/dash/dashapp/src/pages/AppAPI.tsx
- cli/daemon/dash/dashapp/src/pages/AppDiagram.tsx
- cli/daemon/dash/dashapp/src/pages/AppHome.tsx
- cli/daemon/dash/dashapp/src/pages/SnippetPage.tsx
* Adding banners under the nav bar to make it clear if the websocket connection to the daemon is not active or if you are viewing an app that is not currently running.
It has been reported a few times that it's frustrating when the websocket connection goes down and the user think it's a problem with the app. Also frustrating when daily jumping between multiple and apps and you are viewing an app in the front-end that is not currently running.
**Banner when losing connection to the Encore daemon**
Which can happen if you put the computer into sleep mode and come back to the page later
**Banner the app you are viewing is not currently running**
Happens quite often when you are switching in between multiple apps, often takes a few sec to realize that the app is not running or that you are …
> Show banner if websocket connection is inactive

- runtime/appruntime/config/config.go
- runtime/appruntime/cors/cors.go
- runtime/appruntime/cors/cors_test.go
It's quite common to want to allow-list many origins that match a pattern. A common use case is all Vercel Preview Environments with a certain URL pattern.
This extends our CORS handling to support glob matching on allowed origins.
> cors: support globs in allowed origins

- pkg/make-release/windows/build.bat
We moved the `version` package but missed updating the Windows build script.
> Fix Windows release version numbers

- pkg/pgproxy/pgproxy.go
`encore db shell` fails in some circumstances due to the client requesting GSSAPI encryption.
Properly reject this request so the client continues with authentication methods Encore supports.
Thanks Brian Hechinger for the report!
> pgproxy: reject gssapi encryption

- pkg/make-release/make-release.go
We updated to Go 1.20 with the v2 parser, and that now requires something a symbol `res_search` which was added in GNU libc 2.34 (released 2021-08-02).
Once bumped, the ARM64 linux build works again
> Bump GNU libc to 2.34

- v2/codegen/cuegen/testdata/generic_named_types_svc.cue
- v2/internals/schema/schemautil/schemautil.go
For mutually recursive types we need to track
which declarations we've already seen.
Thanks Juan Álvarez for the report.
> schemautil: fix infinite recursion

- runtime/appruntime/app/app.go
- runtime/appruntime/service/service.go
Since it's running on GCP under the hood it's easier
to unify how we process logs from GCP.
> runtime: fix leveled logging for encore cloud

- v2/parser/apis/selector/selector.go
- v2/parser/apis/selector/selector_test.go
If the target set was empty the logic to check for the "all" selector did not run. Fix this by lifting the check out of the loop.
Thanks Patryk Siemiński for the report.
> selector: fix computation when other is empty

- docs/develop/api-schemas.md
When running an encore app locally, the `encore:"sensitive"` tags are ignored. This is intentional, but was not explained in the documentation.
> Add note about redaction not applying in local dev

- cli/daemon/dash/dash.go
- cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
- cli/daemon/dash/dashapp/src/components/api/SchemaView.tsx
- cli/daemon/dash/dashapp/src/components/api/schema.ts
- docs/develop/auth.md
- parser/encoding/rpc.go
- parser/testdata/auth_handler_invalid_field_source.txt
- runtime/appruntime/shared/etype/unmarshal.go
- v2/codegen/apigen/apigenutil/apigenutil.go
- v2/codegen/apigen/authhandlergen/authhandlergen.go
- v2/codegen/apigen/authhandlergen/testdata/struct.txt
- v2/codegen/internal/genutil/etype.go
- v2/internals/pkginfo/names.go
- v2/internals/schema/schemautil/schemautil.go
- v2/parser/apis/api/apienc/encoding.go
- v2/parser/apis/authhandler/authhandler.go
- v2/parser/apis/authhandler/errors.go
In order to support more types of authentication schemes (in particular [Ory](https://www.ory.sh/)) it's sometimes necessary to use cookie-based authentication. This adds support for reading cookie values for auth handler types.
> Add support for cookies in auth handlers

- e2e-tests/testdata/testscript/pubsub_ref.txt
- runtime/pubsub/refs.go
- runtime/pubsub/subscription.go
- runtime/pubsub/topic.go
Tweak the API to make it easier to mock pubsub references before we release it and lock in the behavior.
> runtime: tweak pubsub refs API

- pkg/golden/golden.go
- v2/app/legacymeta/legacymeta.go
- v2/app/service_discovery.go
- v2/app/testdata/resource_sqldb_outside_svc.txt
- v2/app/validate.go
- v2/app/validate_test.go
- v2/codegen/infragen/infragen.go
- v2/codegen/internal/codegentest/codegentest.go
- v2/parser/apis/api/api.go
- v2/parser/apis/authhandler/authhandler.go
- v2/parser/apis/middleware/middleware.go
- v2/parser/apis/parser.go
- v2/parser/apis/servicestruct/servicestruct.go
- v2/parser/infra/caches/cluster.go
- v2/parser/infra/caches/keyspace.go
- v2/parser/infra/config/config.go
- v2/parser/infra/crons/cron.go
- v2/parser/infra/metrics/metrics.go
- v2/parser/infra/pubsub/subscription.go
- v2/parser/infra/pubsub/topic.go
- v2/parser/infra/secrets/secrets.go
- v2/parser/infra/sqldb/named.go
- v2/parser/infra/sqldb/sqldb.go
- v2/parser/parser.go
- v2/parser/resource/bind.go
- v2/parser/resource/resource.go
- v2/parser/resource/resourceparser/resourceparser.go
- v2/parser/resource/usage/usage_test.go
- v2/v2builder/v2builder.go
Support defining resources in test files even
if the test files themselves aren't part of a service.
Fix this by refactoring the logic to move away from
resource.Package (which is now removed) in favor of
resource binds, which keep track of the file it's declared in.
This is stacked on top of #683.
> Support resources defined in test files

- e2e-tests/testdata/echo_client/js/client.js
- e2e-tests/testdata/echo_client/ts/client.ts
- internal/clientgen/javascript.go
- internal/clientgen/testdata/expected_baseauth_javascript.js
- internal/clientgen/testdata/expected_baseauth_typescript.ts
- internal/clientgen/testdata/expected_javascript.js
- internal/clientgen/testdata/expected_noauth_javascript.js
- internal/clientgen/testdata/expected_noauth_typescript.ts
- internal/clientgen/testdata/expected_typescript.ts
- internal/clientgen/typescript.go
The code worked fine, but it was generating invalid type definitions. Fix this by introducing a helper function `makeRecord` that clears undefined values and narrows down the type.
Thanks Phakorn Kiong for the report.
> clientgen: fix js/ts clients with optional query/headers

- internal/optracker/optracker.go
- v2/compiler/build/build.go
- v2/internals/pkginfo/modresolve.go
It seems in some cases the error list is empty even though there is
an error. It's hard to debug as it's intermittent. Try to handle
this a bit more gracefully so we can track down the root cause.
> Fix possible build failures

- runtime/appruntime/exported/config/config.go
As we add support for deploying an encore app across multiple containers, we need to inject configuration for service discovery and routing.
This PR introduces two additional Runtime config fields which specifies:
* Which Gateways an instance should be running
* Where remote services can be reached
The Gateway/API group feature is not yet implemented, but the idea is to provide common public API gateways for a collection of encore services
> ENC-1448 Add Runtime Configurations for gateways and remote services

- cli/daemon/run/run.go
The user's working directory wasn't being propagated to the binary
running `encore run`, which led to the working directory being
inherited from where the Encore daemon was started.
> cli: set working dir for running apps

- runtime/pubsub/internal/aws/manager.go
- runtime/pubsub/internal/aws/topic.go
- runtime/pubsub/internal/aws/topic_test.go
- runtime/pubsub/internal/azure/topic.go
- runtime/pubsub/internal/encorecloud/manager.go
- runtime/pubsub/internal/gcp/topic.go
- runtime/pubsub/internal/nsq/topic.go
- runtime/pubsub/manager_internal.go
- runtime/pubsub/topic.go
This commit enables support for AWS FIFO queues by adding the two new parameters to the calls to publish; which are required when using FIFO queues which allow for exactly once delivery
1. Providing a grouping ID based on the running instance ID (this is required for FIFO)
2. Providing a unique message ID (this is required for exactly once delivery)
> Support AWS FIFO topics

- cli/daemon/run/infra/infra.go
- go.mod
- go.sum
- runtime/appruntime/exported/config/config.go
- runtime/go.mod
- runtime/go.sum
- runtime/pubsub/internal/aws/topic.go
- runtime/pubsub/internal/aws/topic_test.go
- runtime/pubsub/internal/azure/topic.go
- runtime/pubsub/internal/encorecloud/topic.go
- runtime/pubsub/internal/gcp/topic.go
- runtime/pubsub/internal/nsq/topic.go
- runtime/pubsub/internal/test/topic.go
- runtime/pubsub/internal/types/private.go
- runtime/pubsub/internal/types/public.go
- runtime/pubsub/subscription.go
- runtime/pubsub/topic.go
- v2/app/legacymeta/legacymeta.go
- v2/app/testdata/pubsub_err_ordering_attribute_missing.txt
- v2/app/testdata/pubsub_publish_in_middleware.txt
- v2/parser/infra/pubsub/errors.go
- v2/parser/infra/pubsub/topic.go
This commit adds initial support for ordered pubsub on AWS, GCP and EncoreCloud.
It uses a new `OrderingAttribute` configuration from the topic to extract the ordering key from the message attributes at the time of the publish.
> Implement initial Ordered PubSub Support

- docs/primitives/pubsub.md
- runtime/pubsub/internal/types/public.go
This commit adds the docs for creating ordered pubsub topics and allows the public API generator to expose the OrderingAttribute
> Add docs for Ordered PubSub Topics

- e2e-tests/testdata/echo_client/js/client.js
- e2e-tests/testdata/echo_client/ts/client.ts
- internal/clientgen/javascript.go
- internal/clientgen/testdata/expected_baseauth_javascript.js
- internal/clientgen/testdata/expected_baseauth_typescript.ts
- internal/clientgen/testdata/expected_javascript.js
- internal/clientgen/testdata/expected_noauth_javascript.js
- internal/clientgen/testdata/expected_noauth_typescript.ts
- internal/clientgen/testdata/expected_typescript.ts
- internal/clientgen/typescript.go
This is #719 but with a minor style fixup on top. Thanks @PhakornKiong for implementing this!
Closes #719
> clientgen: allow specifying RequestInit for ts/js clients

- docs/primitives/pubsub.md
- e2e-tests/echo_app_test.go
- e2e-tests/testdata/testscript/pubsub_method_handler.txt
- e2e-tests/testscript_test.go
- runtime/appruntime/apisdk/service/service.go
- runtime/appruntime/apisdk/service/singleton.go
- runtime/pubsub/internal/nsq/topic.go
- runtime/pubsub/subscription.go
- runtime/pubsub/types.go
- v2/app/validate_pubsub.go
- v2/codegen/infragen/infragen.go
- v2/codegen/infragen/pubsubgen/pubsubgen.go
- v2/codegen/infragen/pubsubgen/pubsubgen_test.go
- v2/codegen/infragen/pubsubgen/testdata/basic.txt
- v2/codegen/infragen/pubsubgen/testdata/method_handler.txt
- v2/parser/infra/pubsub/errors.go
- v2/parser/infra/pubsub/subscription.go
This adds support for having Pub/Sub handlers that reference a method on a service struct.
> pubsub: add MethodHandler

- docs/primitives/pubsub.md
- runtime/pubsub/types.go
This commit adds to the subscription docs the information that the `ctx` of the handler will be cancelled after the `AckDeadline` has passed.
Thanks to @Willyham for the suggestion
> Add docs for pubsub consumers around ctx deadlines

- cli/daemon/sqldb/proxy.go
This commit fixes a `nil` pointer error when you try and proxy to a database the daemon doesn't know about.
We already supported it higher up in the function, just missed this possible nil pointer issue.
> Support unknown DB in proxy command

- cli/daemon/run/manager.go
- runtime/appruntime/apisdk/api/call_meta.go
- runtime/appruntime/apisdk/api/server.go
- runtime/appruntime/apisdk/api/svcauth/pkgfn.go
- runtime/appruntime/exported/config/config.go
Currently we default to the `noop` method in service-to-service calls, however this needs to be configurable, so different environments can use different methods.
This commit thus adds an initial version of auth config
> Add configurable service-to-service auth methods

- v2/codegen/apigen/endpointgen/request.go
If the encoding description returns errors it returns
a nil slice, which would then cause a panic due to
index out of bounds. Handle this more gracefully.
Thanks Neal Lathia for the report.
> endpointgen: handle encoding errors better

- v2/parser/apis/grpcservice/directive.go
- v2/parser/apis/grpcservice/endpoints.go
- v2/parser/apis/grpcservice/errors.go
- v2/parser/apis/grpcservice/grpcservice_test.go
- v2/parser/apis/parser.go
- v2/parser/apis/servicestruct/servicestruct.go
This adds the stating point of an *api.GRPCEndpoint resource and
begins emitting that resource based on methods on service structs.
> Begin parsing gRPC endpoints

- docs/how-to/migrate-away.md
Update the link to config.go in migrate-away.md
> fix(docs): broken link to app runtime config

- .github/workflows/release.yml
* Update to latest versions of actions
* Specify tag values explicitly
* Use GitHub cache api
> Fix docker image publish workflow

- .github/dockerimg/Dockerfile
Use the target platform instead of the build platform.
> .github/dockerimg: fix platform mismatch

- v2/parser/infra/sqldb/sqldb.go
The use of kebab_case was a mistake, it should
be aligned with `package_name` identifiers.
I reviewed the build metadata on the platform side and found very limited use of `database-name`
and have reached out to affected applications to
update them.
> sqldb: change database name to snake case

- e2e-tests/testdata/echo_client/ts/client.ts
- internal/clientgen/testdata/expected_baseauth_typescript.ts
- internal/clientgen/testdata/expected_noauth_typescript.ts
- internal/clientgen/testdata/expected_typescript.ts
- internal/clientgen/typescript.go
Adding a `@ts-ignore` comment before the `makeRecord`-function in the generated TS client. 
I get a Typescript compilation error for this function, I can not build my project after generating the client. The reason is that we are adding that function but in my case it is never used, so I get error TS6133: 'makeRecord' is declared but its value is never read.
Another option is to add a `@ts-nocheck` comment at the top of the file but ignoring everything feels a bit scary, then we run the risk of introducing runtime errors instead.
> Ignore TS compile errors for makeRecord function

- cli/daemon/exec_script.go
- cli/daemon/run.go
- cli/daemon/run/errors.go
- cli/daemon/run/run.go
- cli/daemon/run/watch.go
- internal/optracker/optracker.go
- v2/app/testdata/cron_job_definition_init.txt
- v2/app/testdata/cron_job_definition_rpc.txt
- v2/app/testdata/missing_generic_param.txt
- v2/app/testdata/rpc_invalid_header_type.txt
- v2/app/testdata/rpc_invalid_query_type.txt
- v2/app/testdata/rpc_outside_service.txt
- v2/app/testdata/rpc_without_calling.txt
- v2/codegen/apigen/endpointgen/request.go
- v2/internals/schema/schemautil/schemautil.go
- v2/parser/apis/api/api.go
- v2/parser/apis/api/apienc/encoding.go
- v2/parser/apis/api/apienc/errors.go
- v2/parser/apis/api/errors.go
This PR re-adds schema validation for header and query string fields, which in the v1 parser we had, but lost during the v2 rewrite.
It also fixes an issue where we where double sending compiler errors to the CLI.
> Re-add schema validation for Header & Query String fields

- runtime/go.mod
- runtime/go.sum
- runtime/pubsub/internal/aws/topic.go
- runtime/pubsub/internal/aws/topic_test.go
- runtime/pubsub/internal/azure/topic.go
- runtime/pubsub/internal/encorecloud/topic.go
- runtime/pubsub/internal/gcp/topic.go
- runtime/pubsub/internal/nsq/topic.go
- runtime/pubsub/internal/test/topic.go
- runtime/pubsub/internal/types/private.go
- runtime/pubsub/internal/utils/workers.go
- runtime/pubsub/internal/utils/workers_test.go
- runtime/pubsub/subscription.go
- runtime/pubsub/types.go
- v2/app/testdata/pubsub.txt
- v2/parser/infra/pubsub/subscription.go
This commit adds a new `MaxConcurrency` configuration parameter to PubSub subscriptions, allowing the end user to control how parallelizable their subscriptions are.
It  respects batch sizes enforced by the cloud providers, and uses a new `WorkConcurrently` to control fetching of work and processing of work in a way that it respects the `MaxConcurrency` field and will never go _above_ it.
> Add new `MaxConcurrency` to PubSub subscriptions

- runtime/appruntime/apisdk/api/server.go
- runtime/appruntime/apisdk/api/server_test.go
We were being overly cautious about escaping
when it came to characters like `{`, leading to
"endpoint not found" errors when a path contained
such characters.
> api: fix routing for escaped paths

- runtime/config/manager_internal.go
- runtime/config/pkgfn.go
- runtime/pubsub/internal/noop/topic.go
- runtime/pubsub/topic.go
- runtime/storage/cache/manager_internal.go
- runtime/storage/cache/noop_internal.go
- runtime/storage/sqldb/db.go
- runtime/storage/sqldb/manager_internal.go
- runtime/storage/sqldb/stdlib_noop_internal.go
This commit introduces the concept of no-op infrastructure. This is required so that Encore can build a single binary containing all the services, however deploy a container with just a single service running inside it - all infrastructure used by other services which are not running will not work as the container will not be provisioned permissions to that infrastructure. Instead any operations on that infrastructure should result in an error.
> Introduce no-op infrastructure

- cli/cmd/encore/app/create.go
- cli/cmd/encore/auth/auth.go
- cli/internal/browser/browser.go
- cli/internal/login/deviceauth.go
- cli/internal/login/interactive.go
- cli/internal/login/login.go
- cli/internal/platform/api.go
- cli/internal/platform/client.go
- cli/internal/platform/login.go
- internal/env/env.go
This adds support for the OAuth2 device authorization login flow. The flow supports logging in with a different device from where the browser runs, allowing use of the Encore CLI in environments that don't run browsers, like developing over SSH or using GitHub Codespaces/Gitpod.
Thanks Peter Stewart for the suggestion.
> cli: add device auth login flow

- pkg/appfile/appfile.go
This was previously supported via configuration
on the Encore Platform side. With this change it's configurable directly in the `encore.app` file,
making it easier to test as part of the normal PR workflow.
> appfile: support configurable docker base image

- cli/daemon/dash/dash.go
- cli/daemon/run.go
- cli/daemon/run/http.go
- cli/daemon/run/manager.go
- cli/daemon/run/proc_groups.go
- cli/daemon/run/run.go
- e2e-tests/app_test.go
- e2e-tests/echo_app_test.go
This PR is prepping for when locally we run multiple processes of the Encore application, one for each microservice and one for each gateway.
This starts by refactoring our existing `Proc` struct into `ProcGroup` while keeping most of the API the same.
Then within a ProcGroup we introduce the concept of `Proc`'s which can be started independently of each other.
> Refactor proc into procgroup

- cli/daemon/run/proc_groups.go
- cli/daemon/run/run.go
- cli/daemon/run/runtime_config.go
- runtime/appruntime/apisdk/api/gateway.go
- runtime/appruntime/apisdk/api/server.go
- runtime/appruntime/apisdk/api/services.go
- runtime/appruntime/apisdk/app/app.go
- runtime/appruntime/apisdk/service/service.go
- runtime/appruntime/apisdk/service/singleton.go
- runtime/appruntime/exported/config/config.go
- runtime/appruntime/infrasdk/secrets/manager_internal.go
This commit makes the following changes:
- Instances can be defined as gateways and brought up by themselves
- `initService` functions are not being called if the instance isn't hosting that service
- API endpoints are not registered if the instance isn't hosting that service
- Only the gateway logs when it is listening for HTTP requests and the registered endpoints locally - this is to reduce log spam on startup
- Missing secrets as a warning as been moved from the runtime to the daemon (again to reduce duplication)
> Get gateway instances running without Auth

- internal/clientgen/golang.go
- internal/clientgen/testdata/expected_golang.go
- internal/clientgen/testdata/expected_javascript.js
- internal/clientgen/testdata/expected_openapi.json
- internal/clientgen/testdata/expected_typescript.ts
- internal/clientgen/testdata/input.go
Unlike other client generators we weren't properly tracking which namespaces had been emitted
and emitting the rest at the end.
Thanks Jamie MacLeod for the report.
> clientgen: fix golang codegen for types outside svc

- cli/daemon/run/proc_groups.go
- cli/daemon/run/runtime_config.go
- runtime/appruntime/apisdk/api/auth.go
- runtime/appruntime/apisdk/api/auth_remote.go
- runtime/appruntime/apisdk/api/call_meta.go
- runtime/appruntime/apisdk/api/callers.go
- runtime/appruntime/apisdk/api/encore_routes.go
- runtime/appruntime/apisdk/api/gateway.go
- runtime/appruntime/apisdk/api/handler.go
- runtime/appruntime/apisdk/api/server.go
- runtime/appruntime/apisdk/api/services.go
- runtime/appruntime/apisdk/api/transport/http.go
- runtime/appruntime/apisdk/service/service.go
- runtime/appruntime/infrasdk/secrets/manager_internal.go
- runtime/appruntime/infrasdk/secrets/secrets.go
- runtime/appruntime/shared/cfgutil/svc.go
- v2/codegen/infragen/infragen.go
- v2/codegen/infragen/secretsgen/secretsgen.go
This PR adds the ability for an Encore service (or gateway) to make a remote call to another container to run an auth handler.
This is required when the auth handler requires access to infrastructure that only the service it is defined in has access to. So all other containers will route their auth calls to that container.
This PR also fixes an issue where secrets would cause a panic in services when not set, even if those services where not running within the container.
> Remote Auth Handler calls implemented

- runtime/appruntime/apisdk/api/gateway.go
Previously we where rewriting the HTTP `Host` header in the proxy to preserve the original host information - which would allow Encore to perform Host based switching behaviour in downstream services.
However this breaks in CloudRun as the load balancers will then end up rerouting the request back to the proxy - causing an infinite recursion of calls.
> Don't rewrite Host in Gateway proxy

- runtime/appruntime/apisdk/api/call_meta.go
- runtime/appruntime/apisdk/api/server.go
- runtime/appruntime/apisdk/api/svcauth/pkgfn.go
This commit updates the runtime to allow outbound requests to be signed with different auth methods than inbound requests can use.
This is useful in a Kubernetes environment where the API Gateway might use `encore-auth`, but services inside the cluster might use `noop`. In this case the Gateway has to only accept `encore-auth`, but it needs to also load `noop` during system startup to sign the outbound requests it makes.
> Support different outbound SvcAuth methods

- runtime/pubsub/internal/aws/topic.go
- runtime/pubsub/internal/gcp/topic.go
It's causing issues with Cloud Run due to how it interacts with graceful shutdown when Cloud Run attempts to
verify if the new revision is healthy.
> pubsub: remove init-time subscription sanity checks

- v2/app/testdata/rpc_err_any.txt
- v2/internals/schema/schema_parser.go
We weren't handling `any` well as we generally don't support interfaces.
This led to confusing error messages for new users. Fix this.
> schema: parse 'any' into empty interface

- v2/app/testdata/sqldb_outside_svc_test.txt
- v2/app/validate_databases.go
To allow for test-only databases to be used.
Thanks Dan Upton for reporting.
> Allow databases in tests outside services

- cli/cmd/encore/gen.go
We've gotten reports that the command times out.
It's not clear whether it's due to taking a long time to parse
larger projects with a cold cache, or due to a deadlock.
I haven't been able to reproduce the deadlock, so let's start
by bumping the timeout and seeing if that helps.
> cli: bump 'encore gen wrappers timeout'

- runtime/appruntime/infrasdk/metadata/cloud_run_collector.go
- runtime/appruntime/infrasdk/metrics/gcp_cloud_monitoring_exporter.go
This commit adds support for us to deploy into GKE and emit metrics as a [K8S container](https://cloud.google.com/monitoring/api/resources#tag_k8s_container)
> Support GKE in GCP Cloud Monitoring

- cli/daemon/sqldb/docker/docker.go
This adds support for the popular `vector` and `postgis`
extensions and gives us more flexibility in the future.
> docker: use encoredotdev/postgres image

- runtime/pubsub/internal/gcp/clients.go
Newer versions of the `cloud.google.com/go/pubsub` package
no longer permit creating a client without specifying a project id.
Since we don't use the default project id but always use `TopicInProject`
and `SubscriptionInProject`, work around this by specifying a placeholder
project id.
> pubsub: fix 'projectID string is empty' panic

- v2/app/testdata/sqldb_outside_svc.txt
- v2/app/validate.go
Since we now accurately track database usages, we can
relax where they are defined. They can still only be *used*
from within services, to ensure permissions are mapped correctly.
> v2/app: allow dbs to be defined outside svcs

- cli/daemon/sqldb/docker/docker.go
The new encoredotdev/postgres:15 image must be run with root
in order to be able to change the filesystem permissions of the
mounted volume during startup.
> docker: fix permission issue

- cli/daemon/sqldb/docker/docker.go
The bitnami-based docker image turned out to be problematic
for local development. We've addressed this by reverting the
`encoredotdev/postgres:15` image to be based off `postgres`.
Revert the CLI changes to match how the `postgres` image works.
> docker: revert docker base image setup

- cli/cmd/encore/cmdutil/output.go
- cli/cmd/encore/namespace/namespace.go
- cli/daemon/db.go
- cli/daemon/namespace/namespace.go
- cli/daemon/sqldb/cluster.go
- cli/daemon/sqldb/docker/docker.go
- cli/daemon/sqldb/driver.go
- cli/daemon/sqldb/external/external.go
- cli/daemon/sqldb/manager.go
- cli/daemon/sqldb/proxy.go
We've observed permission-related issues when using `colima`
with volume mounts. See if it works better with docker volumes.
Also add output options to `encore ns list` to make CLI tooling easier.
> cli: refactor sqldb ns to use docker volumes

- .devcontainer/scripts/godeps.sh
- .github/workflows/ci.yml
- cli/daemon/redis/redis.go
- pkg/svcproxy/svcproxy.go
The svcproxy held a read lock for the duration of serving a request,
which was problematic when doing live reloads with long-running requests
like WebSockets.
Fix this by resolving the proxy with the mutex and then
forwarding the request without holding the lock.
We were calling `.Addr()` on the miniredis server, but it turns out that panics
if calling it after `.Close()` has been called. Fix this by caching the address in
`Start` and looking it up afterwards.
> miscellaneous fixes

- v2/internals/pkginfo/loader.go
- v2/internals/pkginfo/modresolve.go
We've observed some build issues related to the `std` module when using
the new streaming build cache. It's possible `go packages` is getting confused.
Try to work around this by pre-caching the `std` module like we do for other modules.
> pkginfo: pre-cache stdlib module

- cli/cmd/encore/run.go
Tell cobra that `encore run` accepts no positional args,
for improved command validation.
> Validate args for `encore run`

- cli/cmd/encore/app/link.go
- cli/cmd/encore/cmdutil/cmdutil.go
To simplify linking an existing repository to an Encore app,
fix `encore app link` to create the `encore.app` file if it
does not already exist.
> Support `encore app link` with no `encore.app` file

- runtime/storage/sqldb/db.go
- runtime/storage/sqldb/stdlib.go
This adds a way to use Encore's databases with
libraries that want to call `sql.Open` themselves
(rendering `db.Stdlib()` unsuitable).
Thanks Ivan Vanderbyl for the suggestion.
> sqldb: add RegisterStdlibDriver

- cli/daemon/run/proc_groups.go
- cli/daemon/run/runtime_config.go
- runtime/appruntime/apisdk/api/server.go
- runtime/appruntime/apisdk/cors/cors_test.go
Under a multi-process setup when COR's was being handled by the application and the gateway, which caused the `Allow-Origin` to get duplicated after the preflights; this resulted in the browsers rejecting the requests.
> [ENC-1669] Fix duplicate COR's origin headers

- runtime/pubsub/internal/nsq/topic.go
Fixes a bug in the local pub/sub consumer where `MaxConcurrency` wasn't being honored locally because we were only running a single NSQ handler goroutine.
> pubsub: run consumer in-parallel locally

- cli/cmd/encore/app/initialize.go
- cli/cmd/encore/app/link.go
- cli/cmd/encore/cmdutil/cmdutil.go
This adds a new command, `encore app init`, that initializes
an existing repository by creating a new app on the server
and linking with it.
Stacked on top of #860
> cli: add `encore app init`

- cli/daemon/dash/apiproxy/apiproxy.go
- cli/daemon/dash/server.go
To support the new Stored Requests feature, we need to start storing api requests on the platform. This PR exposes access to  the platform graphql endpoint through the local dev dash /__graphql. We downgrade the access level for these graphql requests to a limited set currently only consisting of reading and storing stored requests.
> ENC-1735 Add graphql proxy to local dev dash

- cli/cmd/encore/k8s/auth.go
- cli/cmd/encore/k8s/config.go
- cli/cmd/encore/k8s/kubernetes.go
- cli/cmd/encore/k8s/types/KUBERNETES_LICENSE.txt
- cli/cmd/encore/k8s/types/README.md
- cli/cmd/encore/k8s/types/clientauthentication_types.go
- cli/cmd/encore/k8s/types/homedir.go
- cli/cmd/encore/k8s/types/meta_types.go
- cli/cmd/encore/k8s/types/runtime_types.go
- cli/cmd/encore/main.go
- cli/internal/platform/api.go
- go.mod
- go.sum
This commit adds a new command to the Encore CLI, which allows Encore to configure your `~/.kube/config` file with all the Kubernetes clusters running in your applications environment.
Once configured, you can use `kubectl` directly from your computer against your Encore provisioned kubernetes clusters, without needing to configure firewalls in your cloud account.
Initially, this command is only available for application owners.
> [ENC-1742] Add `encore kubernetes configure` command

- pkg/traceparser/parser.go
The logger wasn't being initialized, causing panics when
encountering error conditions instead of logging an error.
> traceparser: initialize logger

- runtimes/go/appruntime/shared/cloudtrace/extractors.go
The world is standardizing on Traceparent/Tracestate,
so use those instead of the vendor-specific headers.
This also fixes a tracing issue when using multiple
Cloud Run instances with Cloud Trace's X-Cloud-Trace-Context
header.
> runtime: stop parsing aws/gcp trace headers

- v2/internals/pkginfo/modresolve.go
- v2/internals/pkginfo/modresolve_test.go
If a module depends on a module as well as nested modules,
the module lookup code ended up computing the wrong result
and incorrectly determined a package wasn't part of any module.
Thanks Mark McKenzie for the report.
> pkginfo: fix nested module handling

- docs/deploy/deploying.md
- docs/how-to/cgo.md
- pkg/appfile/appfile.go
This adds the ability to bundle source code into the built
Docker image, and reorganizes the encore.app file slightly
to group build settings together.
> appfile: add build configuration

- runtimes/go/pubsub/internal/nsq/topic.go
AckDeadline wasn't being correctly clamped when using NSQ,
causing subscriptions with an AckDeadline exceeding 15 minutes
to fail.
Thanks Will Demaine for reporting.
> pubsub: clamp AckDeadline for NSQ

- pkg/make-release/windows/build.bat
The runtime was being copied into the wrong folder.
Thanks Dhinesh Devanathan for reporting.
> Fix windows build

- pkg/scrub/scrub.go
- pkg/scrub/scrub_test.go
In certain conditions the scrubbing would end up getting
out of sync with its position in the stream.
Thanks Dan Upton for reporting.
> scrub: fix edge case with nested objects in arrays

- runtimes/go/appruntime/shared/shutdown/shutdown.go
- runtimes/go/appruntime/shared/shutdown/singleton.go
This commit modifies the graceful shutdown system of the Encore runtime such that if we're running inside a Kubernetes pod, we will wait for a period of time after receiving a SIGTERM before we start the shutdown of the running application.
This allows time for Kubernetes to put the pod into a terminating state while external systems such as load balancers get updated that the pod is not in a health state and should not be sent new traffic.
Effectively, this means that the pod will be in a terminating state for the duration of the `graceTerminationPeriodSeconds` value in the pod spec (minus the gracefult shutdown time configured by Encore).
> Support graceful pod termination in Kubernetes

- docs/install.md
The output for the shell doesn't have the prompt. Also updated the minor version to the latest one.
> chore - typo update in the shell output

- runtimes/go/appruntime/shared/reqtrack/reqtrack.go
For large traces it's sometimes too low.
> reqtrack: bump trace stream timeout

- pkg/traceparser/parser_test.go
- runtimes/go/appruntime/apisdk/api/handler_test.go
- runtimes/go/appruntime/exported/experiments/names.go
- runtimes/go/appruntime/exported/trace2/log.go
- runtimes/go/appruntime/exported/trace2/logger.go
- runtimes/go/appruntime/shared/platform/platform.go
- runtimes/go/appruntime/shared/platform/streaming_trace.go
- runtimes/go/appruntime/shared/reqtrack/impl.go
- runtimes/go/appruntime/shared/reqtrack/impl_app.go
- runtimes/go/appruntime/shared/reqtrack/reqtrack.go
- runtimes/go/appruntime/shared/reqtrack/trace_stream.go
- runtimes/go/appruntime/shared/traceprovider/mock_trace/mock_trace.go
- runtimes/go/appruntime/shared/traceprovider/traceprovider.go
This adds a new experiment that enables streaming traces
to the platform as they're happening, as opposed to waiting
for the trace to complete.
> runtime: support streaming traces

- runtimes/go/storage/sqldb/stdlib_wrapper_internal.go
The stdlib integration wasn't marking the queries as having been
traced already. This led to queries being traced twice.
Thanks Charles Winter for the report.
> storage/sqldb: fix duplicate trace spans for stdlib queries

- runtimes/go/appruntime/infrasdk/metrics/metrics.go
Metrics providers don't like when metrics are pushed on irregular
intervals and reject these metrics, causing unnecessary error logs.
> runtime/metrics: don't collect on startup or shutdown

- docs/quick-start.ts.mdx
Assumptions I have taken:
* We will have cloud deploys available when going live with the docs
* We will have TS links for other docs pages that we are linking to from this page. This will be easier then going back to this doc and updating it for every new docs page we add. But before going live we will need to click though everything and check for broken links.
> Add quick start guide for TS

- docs/menu.cue
- docs/primitives/services-and-apis-ts.md
First pass at converting this page https://encore.dev/docs/primitives/services-and-apis  into TS docs.
> Add services and apis docs for TS

- cli/cmd/encore/app/create.go
- cli/cmd/encore/app/create_form.go
- cli/cmd/encore/app/create_test.go
- internal/env/env.go
- Hide TypeScript examples on non-beta builds
- Error if app directory already exists
- Generate wrappers on creation
> Improve 'encore app create' behavior

- v2/compiler/build/build.go
- v2/compiler/build/tests.go
When concurrently building and testing, we would sometimes
get spurious compilation errors due to the code generation
being different between the build modes.
Fix this by using separate work directories for each build mode.
> v2/compiler/build: fix concurrent build+test

- CONTRIBUTING.md
- e2e-tests/testdata/echo_client/js/client.js
- e2e-tests/testdata/echo_client/ts/client.ts
- internal/clientgen/javascript.go
- internal/clientgen/testdata/expected_baseauth_javascript.js
- internal/clientgen/testdata/expected_baseauth_typescript.ts
- internal/clientgen/testdata/expected_javascript.js
- internal/clientgen/testdata/expected_typescript.ts
- internal/clientgen/typescript.go
> Support async functions in for auth generator in TS and JS generated clients

- internal/clientgen/openapi/schema.go
- internal/clientgen/testdata/expected_baseauth_openapi.json
- internal/clientgen/testdata/expected_noauth_openapi.json
- internal/clientgen/testdata/expected_openapi.json
This uses the `encore:"optional"` annotation to report
fields as optional in OpenAPI.
> openapi: report required fields

- internal/clientgen/javascript.go
- internal/clientgen/testdata/expected_baseauth_javascript.js
- internal/clientgen/testdata/expected_baseauth_typescript.ts
- internal/clientgen/testdata/expected_javascript.js
- internal/clientgen/testdata/expected_noauth_javascript.js
- internal/clientgen/testdata/expected_noauth_typescript.ts
- internal/clientgen/testdata/expected_typescript.ts
- internal/clientgen/typescript.go
It adds the User-Agent header to the requests only if the global `window` is undefined, which means the client is running on node.  
Fixes #1020.
> Fix User-Agent for generated client in JS and TS

- cli/cmd/encore/main.go
- cli/cmd/encore/test.go
This adds the ability to pass a `--no-color` flag to `encore test` to disable color output in zerolog. This is useful when displaying output in windows which don't support colors. This is the case for VSCode test output:
The current output of those runs look like this, which makes debugging failed tests extremely difficult:
WARNING: This is not tested, as I couldn't quickly figure out how to do that. Building the binary and attempting to use it caused a daemon version mismatch error though both cli and daemon report the same version (I assume there's some hash checking).
> Add ability to disable color in test log output

- docs/tutorials/booking-system.md
This commit updates the doc to use `go install` instead of `go get` to install `sqlc` in the booking tutorial.
When going through the tutorial, using `go get` would not install the binary of `sqlc`.
> Update sqlc booking-system.md

- docs/develop/auth-keys.md
Changed `our` to `hour` in `auth-keys.md`.
> docs: fix typo

- docs/tutorials/incident-management-tool.md
If we want to keep the editor in the tutorial then we first need to move the code to the example repo from https://github.com/encoredev/example-app-oncall.
The way the new editor works is that it reads the code from https://github.com/encoredev/examples, reading from other repos is not supported right now.
> Replace editor with GitHub link in tutorial

- pkg/builder/builder.go
- runtimes/go/appruntime/infrasdk/metrics/datadog/datadog.go
- runtimes/go/appruntime/infrasdk/metrics/datadog_exporter.go
- runtimes/go/appruntime/infrasdk/metrics/prometheus/prometheus.go
- runtimes/go/appruntime/infrasdk/metrics/prometheus_exporter.go
We've observed the datadog SDK in particular
taking a huge chunk of time spent building.
With such a large SDK it also impacts link time.
Fix this by not compiling in the datadog SDK
when running locally.
> runtime: add build tags for metrics providers

- cli/daemon/run/runtime_config2.go
- tsparser/src/builder/templates/entrypoints/combined/main.handlebars
If two services exposed an endpoint with the same name,
the 'combined' entrypoint would have a name conflict.
This led to only one of the handlers being registered.
Fix this by prefixing the local name with the service name.
Thanks Tucker Hawkinson for the report.
> tsparser: fix endpoint name collision in codegen

- docs/observability/tracing.md
This small contribution improves the documentation for the tracing.md content by correcting some typo/spelling errors.
> docs: corrected typos in tracing.md

- docs/introduction.md
This small contribution improves the documentation for the introduction.md content by correcting some typo errors.
> fix(docs): Fix typos in introduction.md

- runtimes/go/appruntime/apisdk/api/handler.go
- runtimes/go/appruntime/exported/model/request.go
- runtimes/go/appruntime/shared/testsupport/testconfig.go
- runtimes/go/appruntime/shared/testsupport/testsupport.go
- runtimes/go/et/mocking.go
- v2/parser/apis/api/usage.go
This extends the `encore.dev/et` package with the ability
to run middleware prior to invoking a mock.
Thanks to Bill Kennedy for the suggestion.
> runtimes/go: add support for running middleware in mock

- runtimes/go/appruntime/apisdk/api/handler.go
- runtimes/go/appruntime/apisdk/service/singleton.go
Since we now support running middleware with mocks,
we need to resolve the mock when looking up svc structs.
> runtimes/go: fix mock lookup for svc init

- docs/how-to/migrate-away.md
There's a small typo in the 'how to migrate away' encore documentation page. In 'What to expect when migrating away', it says this:
> This means that the changes required to migrate away will be almost exactly the same work you would have needed to do if you hadn't used Encore in the first **placem**, e.g. writing infrastructure boilerplate. There's no added migration cost.
Instead of 'placem' it should be 'place'.
> [FIX] typo in migrate-away.md

- Cargo.lock
- runtimes/core/Cargo.toml
- runtimes/core/src/sqldb/manager.rs
Cloud SQL in particular provides client certs that are
PKCS#1-encoded. The native-tls library assumes the certs
are PKCS#8-encoded. Use the `rsa` crate to convert
the certs to the expected format, if necessary.
> runtimes/core: support PKCS#1 certs

- runtimes/core/src/api/schema/header.rs
- runtimes/core/src/api/schema/query.rs
This makes it so the auth handler isn't called when the
request values for the auth params are present but empty.
This mirrors the Go implementation.
> runtimes/core: ignore empty fields for auth data

- Cargo.lock
- runtimes/js/Cargo.toml
- runtimes/js/src/lib.rs
Can't get it working correctly in all environments at the moment. We'll try to reintroduce it later.
> runtimes/js: remove jemalloc

- docs/primitives/cron-jobs.md
- docs/ts/primitives/cron-jobs.md
update cron job docs to reflect encore cloud free tier limits.
Based on conversation in:
https://discord.com/channels/814482502336905216/1236076710122885241
> docs: update cron job docs to reflect encore cloud free tier limits

- cli/daemon/sqldb/cluster.go
- cli/daemon/sqldb/db.go
- cli/daemon/sqldb/proxy.go
- runtimes/go/appruntime/exported/model/request.go
- runtimes/go/appruntime/shared/testsupport/testsupport.go
- runtimes/go/et/manager_internal.go
- runtimes/go/et/pkgfn.go
- runtimes/go/et/singleton_internal.go
- runtimes/go/et/sqldb.go
- runtimes/go/storage/sqldb/db.go
- runtimes/go/storage/sqldb/manager_internal.go
- runtimes/go/storage/sqldb/sqldb_test.go
- runtimes/go/storage/sqldb/test_db.go
This adds the ability to create fresh, temporary databases for tests.
It changes the test database setup to first create a template database, run the migrations against that, and then uses that as the basis for creating a clone. This is much faster than running the migrations again.
> runtimes/go: add et.NewTestDatabase

- Cargo.lock
- tsparser/Cargo.toml
- tsparser/src/bin/tsparser-encore.rs
- tsparser/src/builder/prepare.rs
- tsparser/src/runtimeresolve/tsconfig.rs
- tsparser/tests/common/mod.rs
- tsparser/tests/parse_tests.rs
- tsparser/tests/testdata/tsconfig.txt
When `tsconfig.json` contains path aliases, we need to perform file extension substitution, as per the official docs [1].
[1]: https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution
Thanks José Souza for the report!
> tsparser: handle file extension substitutions for tsconfig aliases

- runtimes/go/pubsub/internal/gcp/topic.go
- runtimes/go/pubsub/types.go
This PR removes a go-routine from within the gcp pubsub receiver. It could cause messages from ordered subscriptions to be processed out of order.
> gcp: Fix concurrency for ordered, pull-based subscriptions

- docs/other/vs-heroku.md
- docs/other/vs-supabase.md
- docs/other/vs-terraform.md
Fixes a couple of typos I spotted when reading through the docs in the `other` directory 😊
> docs: fix typos

- cli/daemon/db.go
When using `encore db conn-uri --env=local` without
an explicit infra namespace, return a connection string
that resolves to the currently active namespace.
This way, the connection string is portable across Encore
installations.
> cli/daemon: skip db namespace unless explicitly requested

- tsparser/src/legacymeta/schema.rs
- tsparser/src/parser/resources/apis/encoding.rs
- tsparser/src/parser/types/custom.rs
- tsparser/src/parser/types/mod.rs
- tsparser/src/parser/types/snapshots/encore_tsparser__parser__types__tests__resolve_types@basic.ts.snap
- tsparser/src/parser/types/snapshots/encore_tsparser__parser__types__tests__resolve_types@generics.ts.snap
- tsparser/src/parser/types/typ.rs
- tsparser/src/parser/types/type_resolve.rs
- tsparser/tests/testdata/query_header.txt
The parsing of the single-argument versions of
the Query and Header builtins didn't match the
TypeScript type definitions.
> tsparser: fix query/header single-arg parsing

- tsparser/src/parser/resources/infra/sqldb.rs
Otherwise we end up with duplicate database definitions.
> tsparser: treat SQLDatabase.named as reference

- runtimes/core/src/lib.rs
- runtimes/core/src/log/logger.rs
- runtimes/core/src/log/mod.rs
- runtimes/core/src/model/mod.rs
- runtimes/core/src/trace/eventbuf.rs
- runtimes/core/src/trace/protocol.rs
Adds logs rows to traces in typescript
> typescript: add logs to traces

- runtimes/core/src/api/jsonschema/de.rs
- runtimes/core/src/api/jsonschema/mod.rs
- runtimes/core/src/api/schema/body.rs
- runtimes/core/src/api/schema/path.rs
- runtimes/core/src/api/schema/query.rs
Query parameters are always received as strings,
so we need to coerce them into the appropriate basic type.
> runtimes/core: coerce strings for query params

- runtimes/core/src/trace/log.rs
It's required for the platform to record stats correctly
> runtimes/core: set x-encore-deploy-id

- runtimes/core/src/api/schema/encoding.rs
- runtimes/core/src/api/schema/path.rs
This is more robust now that we've improved the type parser
> runtimes/core: use path param types

- proto/encore/parser/meta/v1/meta.proto
- runtimes/core/src/api/endpoint.rs
- runtimes/core/src/trace/eventbuf.rs
- runtimes/js/encore.dev/api/mod.ts
- tsparser/litparser/src/lib.rs
- tsparser/src/builder/transpiler.rs
- tsparser/src/legacymeta/mod.rs
- tsparser/src/parser/resources/apis/api.rs
- tsparser/src/parser/resources/parseutil.rs
- tsparser/src/parser/usageparser/mod.rs
This adds the ability to customize the request body limit in Encore.ts, using the `bodyLimit?: number | null` option.
> Support configurable body limit

- runtimes/core/src/log/mod.rs
Since we have several targets prefixed with `encore_`, like `encore_runtime_core` and `encore_js_runtime`.
We could also specify them all rather that use the prefix if we want more control.
> set level for all targets prefixed with encore_

- cli/cmd/encore/run.go
We changed the default value of debug to "", but the code was still
checking for "none". This led to watch mode being disabled even
when debugging is disabled.
> cli/cmd/encore: fix watch mode

- runtimes/core/src/api/gateway/mod.rs
- runtimes/core/src/api/manager.rs
- runtimes/core/src/log/mod.rs
The downside of this is that pingora will silently fail if the address in not bindable (or it will log out that it is trying to bind, and after 30 tries it will log out that is has failed, but we currently filter out those logs)
> runtimes/core: Remove temporary bind of gateway listener

- docs/develop/app-structure.md
Change `coard` to `card` in the documentation
> fix: fix typo in app-structure.md

- tsparser/src/legacymeta/schema.rs
Fix client generation from go to ts when we add go tags
> tsparser: go tag pairs should be separated by colon

- internal/clientgen/typescript.go
Fixes wrapping list of unions with parentheses
```ts
interface Response {
message: string;
item?: Item;
}
interface X {
a: string;
}
interface Y {
b: (keyof X)[];
}
type Thing = { a: string; b: number };
type Item = {
keys: (keyof Thing)[];
otherField: ((X & Y) | X | Y)[];
};
```
Now generates the following type:
```ts
export interface Item {
keys: ("a" | "b")[]
otherField: ({
a: string
b: "a"[]
} | X | Y)[]
}
```
> clientgen/typescript: Add parentheses when lists element type is union

- cli/cmd/encore/main.go
Log out the raw line if json decoding fails
E.g when using `console.log({ hello: "world"})` an event will be emitted with invalid json (key name not quoted)
Fixes #1308
> Log raw log line when json formatting fails

- Cargo.lock
- Cargo.toml
- runtimes/core/Cargo.toml
- runtimes/core/src/api/gateway/mod.rs
Updates to latest version of pingora (0.3.0) and patches it with windows support from https://github.com/cloudflare/pingora/pull/344
Tested on windows with the typescript hello world app
> Update pingora with windows support

- Cargo.lock
- runtimes/core/Cargo.toml
- runtimes/js/Cargo.toml
- tsparser/Cargo.toml
- tsparser/litparser-derive/Cargo.toml
Noticed that we have a bunch of dependencies that are not in use, so thought it would be good to clean up a bit (with the help of cargo machete).
I left `openssl` in core due to the comment here: https://github.com/encoredev/encore/blob/4b15a2eed29ea6d616bab85ab9822728349249af/runtimes/core/Cargo.toml#L65-L66
I assume that should be left in there?
> Cleanup unused cargo dependencies

- runtimes/core/src/api/call.rs
- runtimes/core/src/api/manager.rs
- runtimes/core/src/lib.rs
- runtimes/js/encore.dev/internal/runtime/mod.ts
- runtimes/js/src/runtime.rs
When the runtime starts up it by default begins listening to
HTTP requests and so on. But when running in a worker thread
this is undesirable. To support this use case, tell the runtime
on startup whether it's running in a worker or not and disable
listening for ports if that's the case.
> runtimes/core: handle worker mode

- tsparser/src/builder/codegen.rs
Solves the problem when using npm workspaces, where `encore run` errors with:
```
compile error: ✘ [ERROR] Could not resolve "../../../../apps/encore-app/hello/hello"
encore.gen/internal/entrypoints/combined/main.ts:3:37:
3 │ ... as hello_getImpl } from "../../../../apps/encore-app/hello/hello";
```
(adds the relative path to the app from node modules (../app/encore-app))
This simplifies the codegen import path calculation, tested with both a normal npm project and a npm workspace project. Not sure if there is any other use case that I have missed, or why we involve the relative path from `node_modules` to the app in the import path?
EDIT: tested with yarn as package manager and it work as well
> Simplify codegen import paths

- runtimes/js/encore.dev/internal/runtime/mod.ts
Variable `isMainThread` is `false` in tests, causing the runtime to setup incorrectly.
> runtimes/js: don't set worker mode in tests

- pkg/dockerbuild/tarcopy.go
- v2/compiler/build/build.go
When ejecting from windows, the cross compiled linux binary does not get executable
> eject: make sure the go binary is executable on windows

- go.mod
- go.sum
Ejecting with base image on windows fails when ejecting a second time with this error:
```
12:32AM ERR unable to save docker image error="error loading image: error during connect: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.43/images/load?quiet=0": unable to calculate manifest: blob sha256:45bf31d0bd4a2065a74e1d6cbabd65d747f3e7bfe983be0b6ecf452d39dfefde not found"
```
Updating to the latest version of go-containerregistry seems to solve the problem
> Bump go-containerregistry

- cli/daemon/test.go
Set a default log level for both runtime logs and encore log to error so that tests doesn't emit unnecessary logs
Can still be overridden by setting them when running the tests:
```
ENCORE_LOG=trace ENCORE_RUNTIME_LOG=trace encore test
```
> daemon: set a default log level in tests

- tsparser/src/parser/resources/apis/authhandler.rs
- tsparser/src/parser/resources/apis/encoding.rs
Adds an error if the authHandler parameter type consist of unsupported fields types. Errors out like:
```
error: authHandler parameter type can only consist of Query and Header fields
--> /home/fredr/projects/encore-apps/hellots/hello/hello.ts:47:3
|
47 |   userID: string;
|   ^^^^^^^^^^^^^^^
```
> tsparser: error when auth handler have unsupported fields

- docs/ts/primitives/databases.md
The database docs call out using `queryRow` to query a single row, but the example uses `query`.  This led to confusion when I was getting up to speed with the database section since `query` didn't work for a single row.
This PR changes the docs to use `queryRow` in the example.
Also fixes a small typo I found a couple lines below! 😄
> TS Database Docs: Fix example database query for single row

- internal/clientgen/golang.go
- internal/clientgen/openapi/openapi.go
Streaming endpoints are not yet supported in go client and openapi
> clientgen: skip streaming endpoints in unsupported langs

- cli/cmd/encore/gen.go
We have recently had problems with timing out the api client generation. This increases the timeout from 5 to 15 seconds.
> fix: increase timeout for api client generation

- runtimes/js/src/raw_api.rs
- runtimes/js/src/stream/read.rs
It can lead to a race in `node:stream` causing the final data
to not be read in certain circumstances.
Fixes #1374
> runtimes/js: don't destroy stream after done

- internal/clientgen/testdata/tsapp/expected_list_of_union_javascript.js
- internal/clientgen/testdata/tsapp/expected_list_of_union_typescript.ts
- internal/clientgen/testdata/tsapp/expected_stream_javascript.js
- internal/clientgen/testdata/tsapp/expected_stream_typescript.ts
- parser/encoding/rpc.go
Only default to snake case in go apps
> parser: keep case for query paramters in typescript

- Cargo.lock
- tsparser/Cargo.toml
- tsparser/src/builder/package_mgmt.rs
Windows requires Developer Mode to be enabled to use
symlinks without admin permissions. This isn't always enabled,
so fall back to using junction points if symlink creation fails.
This is for example what rustup does already.
See rust-lang/rustup#3687 for example.
> tsparser: fall back to junction points on windows

- runtimes/js/encore.dev/internal/api/node_http.ts
If you immediately called close() on a raw response writer,
the runtime wouldn't pick up any changes to the status code
made by assigning directly to `resp.statusCode`.
> runtimes/js: flush headers on early close

- tsparser/src/parser/parser.rs
For now, ignore tests to make the usage parsing more permissible.
> tsparser: ignore tests

- internal/clientgen/openapi/openapi.go
Currently, the OpenAPI spec includes private endpoints, which aren't accessible outside of the server. This change removes private endpoints from the spec.
> Only include non-private endpoints in OpenAPI spec output

- tsparser/src/parser/types/type_resolve.rs
So that you can do e.g. `{"some-key": string}`.
> tsparser: support string literal members

- internal/clientgen/openapi/openapi.go
Reverts encoredev/encore#1419
This was done a bit hastily. There are valid use cases for documenting private endpoints. Filtering out private endpoints should be made an option, not the default.
> Revert "Only include non-private endpoints in OpenAPI spec output"

- pkg/encorebuild/compile/compile.go
Reverts to the old behavior of only using zig on cross compiles or releases, and not on local builds
> encorebuild: only use zig when cross compiling or on release

- tsparser/src/parser/module_loader.rs
- tsparser/src/parser/parser.rs
- tsparser/src/parser/types/object.rs
- tsparser/src/parser/usageparser/mod.rs
Only try to parse imports with certain file extensions as modules, and handle errors when module loading fails with swc for better error messages
> Allow importing json files and handle module loader errors better

- tsparser/src/parser/resources/infra/secret.rs
Check if secret is defined within a function and gives a error referencing the secret with a note referencing the function 
```
error: secrets must be defined globally
--> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:36:27
|
36 |       const githubToken = secret("GitHubAPIToken");
|                           ^^^^^^^^^^^^^^^^^^^^^^^^
|
note: secret defined within this function
--> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:27:3
|
27 | /   async ({ name }: { name: string }): Promise<Response> => {
28 | |     try {
29 | |       // ..
30 | |       // ..
...  |
41 | |     }
42 | |   },
| |___^
```
> tsparser: better errors when defining secrets

- Cargo.lock
- internal/clientgen/testdata/tsapp/expected_stream_javascript.js
- internal/clientgen/testdata/tsapp/expected_stream_typescript.ts
- internal/clientgen/testdata/tsapp/input_stream.ts
- tsparser/Cargo.toml
- tsparser/src/app/mod.rs
- tsparser/src/parser/resources/apis/api.rs
Example error:
```
error: api endpoints with conflicting paths defined
--> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:29:22
|
29 |   export const same2 = api(
|  ______________________^
30 | |   { expose: true, method: "POST", path: "/same/:hello" },
31 | |   async ({ hello }: { hello: string }) => {},
32 | | );
| |_^
|
note: previously defined here
--> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:25:22
|
25 |   export const same1 = api(
|  ______________________^
26 | |   { expose: true, method: "POST", path: "/same/:id" },
27 | |   async ({ id }: { id: string }) => {},
28 | | );
| |_^
```
> tsparser: detect conflicting paths in endpoints

- internal/version/version.go
It seems to cause spurious "configuration change" restarts
for some users. Not entirely sure why yet.
> internal/version: remove PATH arg

- .devcontainer/Dockerfile
- Fixes encoredev/encore#1475
- opening project in Codespace requires Go 1.21, as it uses strings.CutPrefix
> .devcontainer: upgrade to go 1.21

- cli/cmd/encore/cmdutil/daemon.go
- internal/version/version.go
Reintroduce the check, but this time with the original path
in case it gets changed at runtime.
> internal/version: capture original path

- .devcontainer/Dockerfile
- Thought I'd go conservative with https://github.com/encoredev/encore/pull/1476, as I thought that was all that was needed
- But now getting this when trying to open a codespace:
```shell
2024-10-14 16:54:48.017Z: #11 47.24 go: honnef.co/go/tools/cmd/staticcheck@master: honnef.co/go/tools@v0.6.0-0.dev.0.20241004131735-f6581d960da8 requires go >= 1.22.1 (running go 1.21.13; GOTOOLCHAIN=local)2024-10-14 16:54:48.018Z: 
```
- Thought there might be other libraries that have similar requirements, so updated to 1.23
> .devcontainer: upgrade to go 1.23

- cli/daemon/run/exec_script.go
- cli/daemon/run/run.go
This wasn't a big problem for Go errors as we only
reported the first line, but it was problematic for TypeScript
errors which duplicated the full error output.
> cli/daemon/run: avoid double-reporting parse errors

- Cargo.lock
- runtimes/core/Cargo.toml
- runtimes/core/src/api/call.rs
- runtimes/core/src/api/endpoint.rs
- runtimes/core/src/api/manager.rs
- runtimes/core/src/api/mod.rs
- runtimes/core/src/api/schema/body.rs
- runtimes/core/src/api/schema/encoding.rs
- runtimes/core/src/api/schema/header.rs
- runtimes/core/src/api/schema/mod.rs
- runtimes/core/src/api/schema/query.rs
- runtimes/core/src/api/websocket.rs
- runtimes/core/src/api/websocket_client.rs
- runtimes/js/Cargo.toml
- runtimes/js/encore.dev/api/mod.ts
- runtimes/js/encore.dev/internal/api/mod.ts
- runtimes/js/encore.dev/internal/appinit/mod.ts
- runtimes/js/encore.dev/internal/codegen/api.ts
- runtimes/js/src/api.rs
- runtimes/js/src/runtime.rs
- runtimes/js/src/websocket_api.rs
- tsparser/src/builder/codegen.rs
- tsparser/src/builder/templates/catalog/clients/endpoints_d_ts.handlebars
- tsparser/src/builder/templates/catalog/clients/endpoints_js.handlebars
- tsparser/src/builder/templates/catalog/clients/endpoints_testing_js.handlebars
- tsparser/src/builder/templates/entrypoints/combined/main.handlebars
- tsparser/src/builder/templates/entrypoints/services/main.handlebars
- tsparser/src/parser/resources/apis/api.rs
- tsparser/src/parser/resources/apis/encoding.rs
Adds a service to service stream client in core and adds it to runtimes/js
> runtimes/core: stream service to service

- cli/daemon/run/exec_script.go
- cli/daemon/run/proc_groups.go
- internal/lookpath/lookpath.go
- v2/tsbuilder/tsbuilder.go
Instead of using the daemon's PATH, use the PATH
from the client's environment. That way we don't need
to restart the daemon on PATH changes, while still
resolving e.g. the correct node binary when using nvm.
> cli: look up binaries using client PATH

- pkg/encorebuild/buildconf/config.go
- pkg/encorebuild/cmd/build-local-binary/build-local-binary.go
- pkg/encorebuild/compile/compile.go
- runtimes/js/.gitignore
This to make it easier when building a dev runtime locally
> make it possible to override what rust builder to use

- cli/daemon/sqldb/db.go
- cli/daemon/sqldb/migrate.go
Refactors and exports the database migration logic so we can reuse it in the Encore Platform. This is mainly to ensure consistency between platform deploys and local runs.
> Share the db migration logic between the Encore platform and the daemon

- Cargo.lock
- Cargo.toml
- runtimes/core/Cargo.toml
- supervisor/Cargo.toml
pingora 0.4.0 includes our windows changes, so we no longer need the branch
> Upgrade pingora to latest released version

- pkg/dockerbuild/spec.go
- pkg/dockerbuild/tarcopy.go
Handles the case when e.g encore is installed on C: and the app is created on D:
> windows: handle the runtime and app is on different drives

- tsparser/src/parser/resources/apis/service.rs
Make the check more specific by checking that the new expression is the default export
> tsparser: fix is_default_export check

- e2e-tests/testdata/echo_client/ts/client.ts
- internal/clientgen/testdata/goapp/expected_typescript.ts
- internal/clientgen/typescript.go
Qualify Response with `globalThis` to avoid name conflicts with types used within that service.
[globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) is available in all browsers and in nodejs
> clientgen/ts: qualify Request with globalThis to avoid name conflicts

- tsparser/src/legacymeta/mod.rs
- tsparser/src/parser/resources/apis/api.rs
- tsparser/src/parser/usageparser/mod.rs
This makes the `tags` field always set, in line with what the runtime expects. Otherwise we can end up with type errors when tags are undefined.
Thanks Daan Kets for reporting.
> tsparser: make tags non-nullable

- runtimes/core/src/api/schema/encoding.rs
Previously we did not parse the handshake request for data if the handshake only consisted of path parameters
> runtimes/core: fix stream handshake with only path parameters

- e2e-tests/testdata/echo_client/js/client.js
- e2e-tests/testdata/echo_client/ts/client.ts
- internal/clientgen/javascript.go
- internal/clientgen/testdata/goapp/expected_baseauth_javascript.js
- internal/clientgen/testdata/goapp/expected_baseauth_typescript.ts
- internal/clientgen/testdata/goapp/expected_javascript.js
- internal/clientgen/testdata/goapp/expected_noauth_javascript.js
- internal/clientgen/testdata/goapp/expected_noauth_typescript.ts
- internal/clientgen/testdata/goapp/expected_typescript.ts
- internal/clientgen/testdata/tsapp/expected_javascript.js
- internal/clientgen/testdata/tsapp/expected_list_of_union_javascript.js
- internal/clientgen/testdata/tsapp/expected_list_of_union_typescript.ts
- internal/clientgen/testdata/tsapp/expected_stream_javascript.js
- internal/clientgen/testdata/tsapp/expected_stream_typescript.ts
- internal/clientgen/testdata/tsapp/expected_typescript.ts
- internal/clientgen/typescript.go
node-fetch will automatically figure out the content type (such as `FormData`) and handle it for certain types, see https://fetch.spec.whatwg.org/#concept-bodyinit-extract and it seems like relying on that logic for raw endoints would be a sane default
> clientgen/{ts,js}: default content type on raw request

- runtimes/core/src/api/error.rs
- runtimes/js/src/error.rs
- runtimes/js/src/pvalue.rs
- runtimes/js/src/runtime.rs
This adds support for Date-fields in error details
Since we don't have a schema for the details field, we deserialize it as `any`. We will lose the type infromation for date fields, and they will then be represented as strings instead.
> parse error details as pvalues to support dates

- runtimes/core/src/api/endpoint.rs
- runtimes/js/encore.dev/req_meta.ts
- runtimes/js/src/request_meta.rs
Add tags to api descriptions so that the can be accessed via middleware and endpoint handlers
> runtimes/js: add tags to api description

- docs/ts/how-to/nestjs.md
- tsparser/txtar/README.md
I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3
> chore: correct typos docs

- runtimes/core/src/api/error.rs
- runtimes/core/src/api/jsonschema/mod.rs
If we can't deserialize error details as pvalues, set them to null (e.g if they are null)
> runtimes/core: deserialize details to none if not valid pvalues

- runtimes/core/src/api/reqauth/meta.rs
`HeaderValue::to_str` errors if there are non-visible us ascii characters in the header value, see https://docs.rs/http/latest/http/header/struct.HeaderValue.html#method.to_str
```ts
export const auth = authHandler<AuthParams, AuthData>(async (params) => {
return { userID: "🎅", name: "åäöテポกขฃคฅฆ🧜" };
});
```
Tested locally with emojis and non-us chars, and can get them out via `getAuthData()` from the above auth handler:
```
6:09PM INF starting request endpoint=get service=hello span_id=clce60omtmpes trace_id=m2g95q064peir9gm2cgub8gsv4 uid="🎅" x_correlation_id=dash-call-1
{ name: 'åäöテポกขฃคฅฆ🧜', userID: '🎅' }
```
> extract non-visible ascii from header value

- runtimes/core/src/api/endpoint.rs
- runtimes/core/src/api/reqauth/platform.rs
When we create the sign in go, we use the decoded path, so make sure we decode it before verify, otherwise paths like `/åäö` will fail verification.
> runtimes/core: decode path before verifying seal

- cli/cmd/encore/cmdutil/daemon.go
Generating debug metadata for large apps fails due to default gRPC message size limits:
```
git:(main) encore debug meta --format json
error: grpc: received message larger than max (6181042 vs. 4194304)
```
This increases the limit from 4mb to 16mb.
> Increase max message size

- pkg/emulators/storage/gcsemu/filestore.go
on windows the separator in \\, so it will not be stripped
> gcsemu: trim os path separator

- tsparser/src/app/mod.rs
- tsparser/src/parser/resources/apis/api.rs
- tsparser/src/parser/usageparser/mod.rs
emit error when two endpoints with the same name are defined within the same service
```
error: api endpoints with conflicting names defined within the same service
--> /home/fredr/projects/encore-apps/ts-tags/other/otherfile.ts:3:14
|
3  | export const get1 = api(
|              ^^^^
|
note: previously defined here
--> /home/fredr/projects/encore-apps/ts-tags/other/other.ts:18:14
|
18 | export const get1 = api(
|              ^^^^
```
> tsparser: duplicate api name error

- docs/ts/tutorials/graphql.mdx
In the GraphQL tutorial for encore.ts, the schema filename specified in the codegen config does not match the one that the tutorial asks us to create.
> Fix schema filename mismatch in TypeScript GraphQL tutorial

- pkg/builder/builder.go
- v2/tsbuilder/tsbuilder.go
This will make it easier to configure where build errors are redirected, for use in e.g. Encore Cloud CI pipelines.
> builder: make Stderr configurable

- runtimes/go/beta/errs/error.go
I'd like to be able to embed the `errs.Error` struct without losing the error metadata when the handlers in `errs` are used. Currently, if I try to use an error struct with an embedded `*errs.Error` struct, the type assertions fail and the error metadata is lost. 
The use case is a bit niche, but if this change is controversial I can go into more details.
> [errs] use errors.As instead of type assertions

- cli/cmd/encore/exec.go
- docs/go/cli/cli-reference.md
- docs/menu.cue
- docs/ts/cli/cli-reference.md
- docs/ts/develop/running-scripts.md
- docs/ts/develop/tools.md
Add some docs for the exec cli command for go and ts.
Also deprecate the alpha version of the command and refer to using the non-alpha version.
> add docs for exec cli

- runtimes/core/src/sqldb/val.rs
I accidentally remove the accepts on the wrong place in https://github.com/encoredev/encore/pull/1856
:facepalm: sorry
The PValue implenetation should not call the PValue implementation, but the RowValue should call the PValue implementation
> fix correct accepts

- Cargo.lock
- Cargo.toml
- docs/ts/primitives/databases.md
- runtimes/core/src/sqldb/client.rs
- runtimes/core/src/sqldb/mod.rs
- runtimes/core/src/sqldb/transaction.rs
- runtimes/js/encore.dev/storage/sqldb/database.ts
- runtimes/js/src/sqldb.rs
Adds support for transactions in runtimes/core and runtimes/js
We should probably merge https://github.com/encoredev/rust-postgres/pull/1 and update Cargo.toml again. (suggested that change upstream as well https://github.com/sfackler/rust-postgres/pull/1230)
> database transaction support in typescript

- pkg/clientgen/golang.go
- pkg/clientgen/testdata/tsapp/expected_golang.go
This PR addresses a problem with Go client generation from a Typescript API. Currently naming of RPC functions and parameters are taken straight from the Typescript codebase. This is a problem because in Typescript these typically start with lowercase characters, making them private and unaccessible in Go.
This PR fixes that by making sure that the first letter is always capitalized for:
- RPC function names
- RPC parameters
Ideally client generation the other way around (from Go code to Typescript) would also follow Typescript naming conventions of using `camelCase`. Currently it just takes the casing from Go, which means it usually is `PascalCase`. 
I would be happy to submit a PR for this, but also realize this could have backwards compatibility issues so wanted to get your thoughts on …
> fix/make RPC functions and parameters accessible in generated Go client

- .github/workflows/ci.yml
- .github/workflows/release.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
> ci: bump actions/checkout to v4

- runtimes/js/src/raw_api.rs
subtle difference, 
```
for (k, v) in headers
```
yeilds each key only once, for multiple values it will be set to None the second time
```
for (k, v) in headers.iter()
```
yeilds the same key for each value (https://docs.rs/http/latest/http/header/struct.HeaderMap.html#method.iter)
> runtimes/js: fix setting of multi-headers

- runtimes/core/src/api/call.rs
- runtimes/core/src/api/manager.rs
- runtimes/js/encore.dev/api/mod.ts
- runtimes/js/encore.dev/internal/api/mod.ts
- runtimes/js/encore.dev/mod.ts
- runtimes/js/src/pvalue.rs
- runtimes/js/src/runtime.rs
- tsparser/src/builder/codegen.rs
- tsparser/src/builder/templates/catalog/auth/auth_ts.handlebars
- tsparser/src/builder/templates/catalog/clients/endpoints_d_ts.handlebars
- tsparser/src/builder/templates/catalog/clients/endpoints_js.handlebars
- tsparser/src/builder/templates/catalog/clients/endpoints_testing_js.handlebars
Adds call options for api calls that can be used to set options when calling apis. For now only adds a way of overriding auth data, mainly for, but not limited to, mocking when calling via ~encore/clients in tests.
> runtimes/{js,core}: add call options to api calls

- runtimes/js/encore.dev/api/mod.ts
when using the `middleware` helper, we need to make sure we don't mutate the passed middleware with options.
Currently if a middleware is used from two services, one service will override the other services middleware options. This should prevent that from happening.
> ts middleware: do not mutate the middleware when constructing

- Cargo.lock
- Cargo.toml
- runtimes/core/Cargo.toml
- runtimes/core/src/sqldb/val.rs
- runtimes/js/src/sqldb.rs
updates our rust-postgres patch branch to one that is rebased on latest master so we get the integration with the `cidr` crate.
> runtimes/core/sqldb: add cidr and inet postgres types

- Cargo.lock
- runtimes/core/src/log/mod.rs
Add more logging when db proxying fails. This is especially when using ORMs that bypasses our checks when calling through the runtime. Adds this: https://github.com/encoredev/rust-postgres/pull/2
> db proxy: better logging

- .github/workflows/ci.yml
We are getting failures on this step, see e.g https://github.com/encoredev/encore/actions/runs/16312896373/job/46081988889?pr=2007
When running the command locally, this solves the problem, but locally I get a slightly different error message:
```
curl: (3) URL rejected: Malformed input to a URL function
```
So might be a different problem
> Fix CI step "Install encore-go"

- runtimes/go/request.go
Add http method to the request model so it can be read from e.g middlewares
Fixes #2031
> runtimes/go: add method to request

- runtimes/go/appruntime/apisdk/api/handler.go
- v2/codegen/apigen/endpointgen/response.go
- v2/codegen/apigen/endpointgen/testdata/response_status.txt
- v2/internals/schema/schemautil/schemautil.go
- v2/parser/apis/api/apienc/encoding.go
- v2/parser/apis/api/apienc/errors.go
When hosting one process per service we failed the request as it wasn't 200, and we didnt decode the field into the struct 
Refactored the http status field code to be more similar to the rest of the parameter encoding fields, so that we can get the type in the code gen and cast the status to it
> runtimes/go: fix custom http status on external service to service calls

- Cargo.lock
cherry-picked https://github.com/swc-project/swc/pull/11094
fixes this error when building:
```
error[E0432]: unresolved import `serde::__private`
--> /home/fredr/.cargo/git/checkouts/swc-804afb9566b98614/58b2ecd/crates/swc_common/src/private/mod.rs:3:9
|
3 | pub use serde::__private as serde;
|         ^^^^^^^---------^^^^^^^^^
|         |      |
|         |      help: a similar name exists in the module: `private`
|         no `__private` in the root
```
https://github.com/encoredev/swc/commit/3ccddcb7d70380b6952296717b2d9f2056f4c2ac
> fix swc build
