cli/daemon/daemon.go
cli/daemon/db.go
cli/daemon/internal/runlog/runlog.go
cli/daemon/run.go
cli/daemon/sqldb/cluster.go

Improve the user experience by displaying what Encore is doing behind the scenes.

cli/daemon: improve 'encore run' UX

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/scripts/godeps.sh
.devcontainer/scripts/install.sh
.devcontainer/scripts/prepare.sh

This adds support for GitHub Codespaces for simplifying
editing and contributing to Encore.

.devcontainer: add folder

---

cli/internal/wgtunnel/wgtunnel_darwin.go
cli/internal/wgtunnel/wgtunnel_linux.go
go.mod
go.sum

Please refer https://github.com/encoredev/encore/issues/57

Updated golang.zx2c4.com/wireguard Fixes #57

---

cli/daemon/dash/dashapp/src/components/api/RPCCaller.tsx
cli/daemon/dash/dashapp/src/lib/base64.ts

cli/daemon/dash/dashapp: fix base64 encoding of unicode

---

docs/docs.cue
docs/how-to/share-db-between-services.md

- Documents possibility to share databases between services
- Adds example on how to execute queries towards other services' databases
closes #101

docs: how to share db between services

---

docs/develop/auth.md
docs/tutorials/rest-api.md

For some reason the docs improvements #79 were lost at some point. This adds them back.﻿

docs/auth: add back missing docs

---

docs/deploy/custom-domains.md
docs/docs.cue

This commit adds the documentation for how to configure custom domains
with Encore applications.

docs: add custom domains documentation

---

compiler/build.go

Add support for specifying additional build tags and the ability
to static link the resulting binary. These changes enable building
more self-contained binaries that can be used in 'scratch' images,
reducing startup time and image sizes.

compiler: support build tags, static linking

---

.github/workflows/go.yml
cli/internal/xos/xos_windows.go

This commit fixes a small typo under windows builds.

Fix Windows builds

---

docs/tutorials/slack-bot.md

Docs: Fix typo in "Building a Slack bot"

---

parser/encoding/request.go
parser/schema.go
parser/util.go

Adds a utility to describe how an RPC request payload should be encoded

parser/encoding: Add request payload utility

---

cli/daemon/run/testdata/echo_client/client.ts
cli/daemon/run/testdata/echo_client/main.ts
cli/internal/codegen/testdata/expected_typescript.ts
cli/internal/codegen/typescript.go

This commit removes the error when auth tokens are blank or
missing.

Typescript Client: Remove error on missing auth token

---

cli/daemon/run/run_test.go
cli/daemon/run/testdata/echo/echo/echo.go
cli/daemon/run/testdata/echo_client/client.ts
cli/daemon/run/testdata/echo_client/client/client.go
compiler/internal/codegen/codegen_main.go
compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
compiler/internal/codegen/testdata/variants.txt

This PR adds logic to handle nil pointers when serializing the response in the generated request handlers.

compiler/internal/codegen: Handle nil pointer responses

---

cli/daemon/sqldb/remote.go
pkg/pgproxy/pgproxy.go

The database proxy code did not properly handle multiple sessions
being initiated. As a result both session resumption and query cancellation
requests were handled incorrectly.
Fix this by changing the proxy to support multiple sessions instead of
just one, and look up the destination for cancellation requests
based on the BackendKeyData.
Fixes #262 #261
Thanks @vilhelmmelkstam and Max D for reporting.

pkg/pgproxy: fix session resumption, cancellation

---

cli/cmd/encore/daemon/daemon.go
cli/daemon/run/run.go
cli/daemon/run/tests.go

The local database configuration did not set max connections.
Fixes #266

Fix local database max connections

---

runtime/appruntime/api/auth.go
runtime/appruntime/api/handler.go
runtime/appruntime/api/reqtrack.go
runtime/appruntime/model/request.go
runtime/appruntime/trace/events.go
runtime/pubsub/subscription.go

This fixes call tracing by propagating DefLoc.

runtime/appruntime: fix call tracing

---

docs/benefits.md
docs/community/index.md
docs/configuration/auth-keys.md
docs/deploy/environments.md
docs/deploy/infra.md
docs/develop/api-docs.md
docs/develop/api-schemas.md
docs/develop/app-structure.md
docs/develop/auth.md
docs/develop/cli-reference.md
docs/develop/client-generation.md
docs/develop/config.md
docs/develop/databases.md
docs/develop/errors.md
docs/develop/pubsub.md
docs/develop/services-and-apis.md
docs/docs.cue
docs/how-to/github.md
docs/how-to/insert-test-data-db.md
docs/how-to/integrate-frontend.md
docs/how-to/migrate-away.md
docs/index.md
docs/introduction.md
docs/observability/tracing.md
docs/quick-start.md
docs/tutorials/rest-api.md
docs/tutorials/slack-bot.md

This syncs the docs folder with the encore.dev/docs site.

docs: sync with website

---

runtime/pubsub/internal/azure/clients.go
runtime/pubsub/internal/azure/topic.go

Fix improperly formatted error messages in azure pubsub implementation

azure: Fix error formatting

---

cli/daemon/dash/dashapp/package-lock.json
cli/daemon/dash/dashapp/package.json
cli/daemon/dash/dashapp/src/App.tsx
cli/daemon/dash/dashapp/src/app.css
cli/daemon/dash/dashapp/src/components/Nav.tsx
cli/daemon/dash/dashapp/src/components/app/AppDiagram.test.tsx
cli/daemon/dash/dashapp/src/components/app/AppDiagram.tsx
cli/daemon/dash/dashapp/src/components/svgElements.tsx
cli/daemon/dash/dashapp/src/lib/graph/dagre-algo.ts
cli/daemon/dash/dashapp/src/lib/graph/elk-algo.ts
cli/daemon/dash/dashapp/src/lib/graph/graph-utils.test.ts
cli/daemon/dash/dashapp/src/lib/graph/graph-utils.ts
cli/daemon/dash/dashapp/tailwind.config.js

- Change the layout algorithm to use [elkjs](https://github.com/kieler/elkjs)
- Hovering a node in the diagram highlights it's descendants
- Refined the styling with Encore branding

Add functionality to system diagram visualisation

---

cli/daemon/dash/dashapp/package-lock.json
cli/daemon/dash/dashapp/package.json
cli/daemon/dash/dashapp/src/components/FlowDiagram/FlowDiagram.test.tsx
cli/daemon/dash/dashapp/src/components/FlowDiagram/FlowDiagram.tsx
cli/daemon/dash/dashapp/src/components/FlowDiagram/algorithms/elk-algo.ts
cli/daemon/dash/dashapp/src/components/FlowDiagram/flow-utils.test.ts
cli/daemon/dash/dashapp/src/components/FlowDiagram/flow-utils.ts
cli/daemon/dash/dashapp/src/components/FlowDiagram/flow.css
cli/daemon/dash/dashapp/src/components/FlowDiagram/flowSvgElements.tsx
cli/daemon/dash/dashapp/src/components/FlowDiagram/useDownloadDiagram.ts
cli/daemon/dash/dashapp/src/pages/AppDiagram.tsx

Update the flow page with things that are now available in on [app.encore.dev](https://app.encore.dev):
* Add screen capture button
* Add CRON jobs

Update flow page with web admin functionality

---

cli/cmd/encore/auth.go
cli/cmd/encore/daemon.go
cli/internal/conf/conf.go

Logout the user if the refresh token of some reason become corrupted

Invalidate corrupt refresh token

---

README.md

Fix Grammatical errors in README.md

Fix Grammatical Errors

---

docs/community/contribute.md
docs/configuration/auth-keys.md
docs/deploy/custom-domains.md
docs/develop/api-schemas.md
docs/develop/auth.md
docs/develop/caching.md
docs/develop/client-generation.md
docs/develop/config.md
docs/develop/databases.md
docs/develop/pubsub.md
docs/develop/secrets.md
docs/develop/services-and-apis.md
docs/docs.cue
docs/how-to/change-db-schema.md
docs/install.md
docs/introduction.md
docs/quick-start.mdx
docs/tutorials/incident-management-tool.md
docs/tutorials/rest-api.md
docs/tutorials/slack-bot.md

docs: sync

---

cli/cmd/encore/version.go

Update install link

---

cli/daemon/dash/dashapp/src/components/api/SchemaView.tsx

With the introduction of pointer type tracking we needed to update the schema rendering to handle these types.
Thanks Juan Álvarez for the bug report.

cli: fix schema rendering of pointer types

---

README.md

I hyperlinked the encore image with its encore's official website, so a user can access website with single click,
Minor but impactful.
Thank you!

README.md : HyperLinking the encore image.

---

cli/daemon/dash/dash.go
cli/daemon/run.go
compiler/internal/codegen/api_handlers.go
compiler/internal/codegen/codegen_encoregen.go
compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
compiler/internal/codegen/testdata/variants.txt
e2e-tests/testdata/echo/di/di.go
e2e-tests/testdata/echo_client/client.ts
e2e-tests/testdata/echo_client/client/client.go
e2e-tests/testdata/echo_client/main.go
parser/parser.go
parser/testdata/rpc_raw_call.txt

- Support raw endpoints on service structs
- Return parser error for calling raw endpoint from another endpoint
- Fix dashboard handling of responses
- Fix panic in version check returning nil

Improve handling of raw endpoints

---

pkg/errinsrc/utils.go

We were treating bailouts as unhandled panics.
Fix this so they're properly unwrapped.

pkg/errinsrc: handle bailouts properly

---

compiler/internal/codegen/auth_handler.go
parser/est/est.go
parser/svc.go
parser/testdata/auth_handler_svc_struct.txt

This adds support for defining auth handlers on service structs.

parser: support auth handler on service structs

---

parser/meta.go

Instead of erroring on down migrations, ignore them.
This allows users to keep down migrations in the
folder even though Encore doesn't currently use them.

parser: ignore down migrations

---

cli/cmd/encore/db.go
cli/daemon/daemon.go
cli/daemon/db.go

cli/cmd/encore: throw error if db doesn't exist

---

cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx
cli/daemon/dash/dashapp/src/components/trace/util.ts

To improve the ability to distinguish between spans.

dashapp: cycle trace span colors

---

cli/daemon/engine/trace/trace.go
runtime/appruntime/model/trace.go
runtime/request.go

Expose trace data in encore.CurrentRequest

---

runtime/appruntime/metrics/encore_cloud_exporter.go

Fix Encore Cloud metrics provider init

---

tools/publicapigen/main.go

Unconditional panics cause static analysis tools to treat
the function as panicking (unsurprisingly). This in turn
means code following a call to an Encore SDK will get
marked as unreachable, which is a very confusing
and frustrating experience as a user.
Fix this by making the panic conditional, and adding
a naked return so the new code actually compiles.
Finally add a check that the generated code compiles.

publicapigen: rework panics

---

runtime/appruntime/api/handler_test.go

Updates `TestDesc_EndToEnd` to use new custom metrics instead of logs-based metrics.

Fix end-to-end test

---

runtime/appruntime/metrics/prometheus/prometheus.go
runtime/appruntime/metrics/prometheus/prometheus_test.go

We need to check if a time series value is valid before exporting it to Prometheus.

Export Prometheus metrics only if set

---

compiler/internal/codegen/api_handlers.go
compiler/internal/codegen/codegen_main.go
compiler/internal/codegen/testdata/TestCodeGenMain__empty.golden
compiler/internal/codegen/testdata/TestCodeGenMain__only_header_auth.golden
compiler/internal/codegen/testdata/TestCodeGenMain__only_query_auth.golden
compiler/internal/codegen/testdata/TestCodeGenMain__token_auth.golden
compiler/internal/codegen/testdata/TestCodeGenMain__variants.golden
compiler/internal/codegen/testdata/TestCodeGen_TestMain__variants.golden
compiler/internal/codegen/testdata/variants.txt
parser/est/est.go
runtime/appruntime/api/server.go
runtime/appruntime/config/config.go
runtime/appruntime/cors/cors.go
runtime/appruntime/cors/cors_test.go

This adds support for adding headers returned by Encore APIs to
CORS Access-Control-Expose-Headers.

Add support for CORS Expose-Headers

---

runtime/appruntime/metrics/aws/cloudwatch.go

Fixes the AWS CloudWatch exporter.

Send metrics to AWS CloudWatch only if valid

---

runtime/appruntime/metrics/gcp/cloud_monitoring.go

The code should read the metrics name from the config: that way, different Encore Cloud apps don't write to the same metric.

Fix Encore Cloud system metrics

---

cli/daemon/dash/dashapp/src/components/Nav.tsx
cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx

Fix for this bug: https://encoredev.slack.com/archives/C0356ERKBEH/p1678374849519439
Also removing the connection banner when changing between apps.

Bugfix for "rendered fewer hooks than expected" exception

---

.github/workflows/go.yml
.github/workflows/release.yml

The new actions/setup-go@v4 action includes caching automatically using actions/cache under the hood - swapping to that.

Attempt to fix windows builds

---

runtime/appruntime/api/handler.go
v2/app/api_framework.go
v2/app/apiframework/apiframework.go
v2/codegen/apigen/authhandlergen/testdata/authdata.txt
v2/codegen/apigen/authhandlergen/testdata/basic.txt
v2/codegen/apigen/authhandlergen/testdata/servicestruct.txt
v2/codegen/apigen/authhandlergen/testdata/struct.txt
v2/codegen/apigen/endpointgen/testdata/api_call.txt
v2/codegen/apigen/endpointgen/testdata/api_call_servicestruct.txt
v2/codegen/apigen/endpointgen/testdata/basic.txt
v2/codegen/apigen/endpointgen/testdata/path_params.txt
v2/codegen/apigen/endpointgen/testdata/raw_endpoint.txt
v2/codegen/apigen/endpointgen/testdata/request_headers.txt
v2/codegen/apigen/endpointgen/testdata/request_params.txt
v2/codegen/apigen/endpointgen/testdata/request_query.txt
v2/codegen/apigen/endpointgen/testdata/response_headers.txt
v2/codegen/apigen/endpointgen/testdata/response_params.txt
v2/codegen/apigen/endpointgen/testdata/service_struct.txt
v2/codegen/apigen/endpointgen/testdata/unexported.txt
v2/codegen/apigen/maingen/testdata/auth_handler.txt
v2/codegen/apigen/maingen/testdata/basic.txt
v2/codegen/apigen/maingen/testdata/service_struct.txt

It's 1-based instead of 0-based.

v2: fix service number allocation

---

runtime/storage/sqldb/db.go

Hi 👋 
This PR attempts to expand upon `sqldb.Driver`, which provides access to `*pgxpool.Pool`, by adding a way to access the underlying `*pgx.Conn` of a connection as well. 
Either implementation offered here would work, and there might be another method I wasn't able to think of. We only need one. I am happy to add tests with some guidance on where they should be.
The addition of `sqldb.Driver` helps when we need lower level access to DB features that pgx provides, such as `COPY FROM STDIN`. However, since the rest of our code expects stdlib's `*sql.DB` interfaces, it becomes all-or-nothing: once we've dropped down to pgx for a transaction, we can't go back to a `*sql.DB` compatible interface for the duration of a transaction.
The addition of access to `*pgx.Conn` would allow us to …

Allow access to underlying *pgx.Conn

---

tools/publicapigen/main.go

Support running the publicapi Encore runtime
without panicking to better support certain
use cases, such as code generation with ent.

publicapigen: tweak output

---

pkg/errinsrc/srcerrors/errors.go
pkg/errors/template.go
v2/internals/perr/perr.go
v2/v2builder/v2builder.go

We were only handling bailouts, not unintended panics.

Improve error handling of panics

---

cli/cmd/git-remote-encore/main.go

This adds the ability to build a separate binary `git-remote-encorelocal` for testing purposes, that talks to a local ssh server instead of `git.encore.dev`.

git-remote-encore: add support for local testing

---

cli/daemon/dash/dashapp/src/components/trace/SpanDetail.tsx
docs/menu.json

Add a new menu.json file for use with the auto-updating
docs system.

Add docs/menu.json, fix trace stack traces

---

docs/primitives/databases.md

The new sqldb.NewDatabase is now the recommended way of creating databases. Update the docs to reflect this.

docs: document sqldb.NewDatabase

---

docs/primitives/pubsub.md
go.mod
go.sum
runtime/go.mod
runtime/go.sum
runtime/pubsub/internal/types/public.go
runtime/pubsub/types.go
tools/publicapigen/main.go

This commits adds the documentation for Exactly Once semantics on pubsub topics

Add Exactly Once docs

---

v2/internals/pkginfo/loader.go

Thanks Luka Giorgadze for the report.

pkginfo: handle go not installed

---

README.md

Update README.md visuals

---

v2/codegen/apigen/endpointgen/testdata/request_params.txt
v2/codegen/internal/genutil/types.go

This commit adds support for arrays to have `omitempty` tagged

Support `omitempty` on arrays

---

runtime/appruntime/apisdk/api/call_meta.go

We've encounted an issue where CloudRun is adding `traceparent` to inbound calls, this is causing an issue with our trace engine which then can't find the parent span.
For now we're going to work around this by simply disabling reading the `traceparent` when it's not coming from an internal service-to-service call.
In the future we want to support this and allow the intergration of other trace systems, but this will fix the issue for right now.

Ignore `traceparent` header if not internal service call

---

cli/cmd/git-remote-encore/main.go
cli/daemon/db.go
cli/daemon/run/proc_groups.go
internal/conf/conf.go

Fix a few different issues with the local daemon:
* Database name lookup in `encore db shell`
* Periodically refresh auth information in daemon
* Fix process kill race in `ProcGroup`

cli/daemon: grab bag of fixes

---

runtime/pubsub/internal/aws/topic.go
runtime/pubsub/internal/gcp/topic.go

This fixes a race with underlying infrastructure
that spins up and shuts down the process in short
succession, triggering graceful shutdown while
the service is still initializing.

pubsub: use separate context for initialization

---

runtime/pubsub/internal/utils/workers.go
runtime/pubsub/internal/utils/workers_test.go

Refactor and simplify workInWorkPool to fix issue
with AWS pubsub deadlocks.

pubsub: simplify concurrent fetcher

---

runtime/pubsub/internal/gcp/topic.go

We've noticed for ExactlyOnce subscriptions with a high MaxConcurrency
number, that the GCP PubSub library fails to pass any messages to our
recieve function. By dropping the number of goroutines we allow the GCP
library to use, we can prevent these problems and recieve messages - so
we've set this always to 10
To maintain the max concurrency limit and allow Encore apps to achieve
the throughput they desire, we then push messages into new goroutines
for each message, relying on the GCP Pub/Sub library to obey the
`MaxConcurrency` number
For anybody else who encounters this, this appeared as a error in our
logs of:
> automatic lease modack retry failed for following IDs
Upon investigation and adding more logging to the GCP Pub/Sub library we
discovered the source error was this:
> modack …

Move our GCP PubSub subscribers to use go routines for processing

---

runtime/pubsub/subscription.go

It's possible to have no-op subscriptions attached to topics
that are themselves not no-op topics. Handle this case properly.

pubsub: handle no-op subscriptions properly

---

e2e-tests/testdata/testscript/graceful_shutdown.txt
runtime/appruntime/apisdk/api/server.go
runtime/appruntime/apisdk/app/app.go
runtime/appruntime/apisdk/service/service.go
runtime/appruntime/apisdk/service/singleton.go
runtime/appruntime/infrasdk/metrics/aws/cloudwatch.go
runtime/appruntime/infrasdk/metrics/datadog/datadog.go
runtime/appruntime/infrasdk/metrics/gcp/cloud_monitoring.go
runtime/appruntime/infrasdk/metrics/metrics.go
runtime/appruntime/infrasdk/metrics/null_exporter.go
runtime/appruntime/infrasdk/metrics/prometheus/prometheus.go
runtime/appruntime/infrasdk/metrics/zzz_singleton_internal.go
runtime/appruntime/shared/encoreenv/app.go
runtime/appruntime/shared/encoreenv/encoreenv.go
runtime/appruntime/shared/encoreenv/noapp.go
runtime/appruntime/shared/shutdown/shutdown.go
runtime/pubsub/manager_internal.go
runtime/pubsub/zzz_singleton_internal.go
runtime/shutdown/shutdown.go
runtime/storage/cache/manager_internal.go
runtime/storage/cache/zzz_singleton_internal.go
runtime/storage/sqldb/db.go
runtime/storage/sqldb/manager_internal.go
runtime/storage/sqldb/zzz_singleton_internal.go

This improves the Encore shutdown behavior and provides additional
information to services about the shutdown process.
Fixes #850

Add encore.dev/shutdown package

---

runtimes/go/appruntime/infrasdk/metrics/datadog/datadog.go

Datadog COUNTER metrics have been submitted as cumulatives, whereas Datadog expects them to receive deltas. Fix this by computing the interval and delta in the Encore Runtime

Compute Datadog Count Deltas

---

runtimes/go/pubsub/internal/nsq/topic.go

Properly model more aspects of the retry policy
when setting up NSQ's consumer config.

nsq: set consumer config

---

runtimes/go/pubsub/internal/nsq/topic.go

We weren't enforcing the nsq limits.

pubsub/nsq: clamp config values

---

docs/how-to/temporal.md

Thanks Cesar Jimenez for the report!

docs: fix typo

---

runtimes/go/appruntime/apisdk/cors/cors.go

It appears to cause CORS issues in some circumstances otherwise. Thanks Aleksandar Faraj for reporting.

cors: add User-Agent as an allowed header

---

docs/go/overview.md
docs/index.mdx
docs/primitives/code-snippets.md
docs/ts/overview.md
docs/tutorials/index.md

This PR updates the Overview page for the Go SDK documentation along with tweaks to the general Docs Overview page.

Update go sdk overview

---

cli/cmd/encore/daemon/daemon.go
cli/daemon/apps/apps.go
cli/daemon/daemon.go
cli/daemon/watch.go
pkg/watcher/watcher.go

- daemon: add pprof server
- Avoid concurrent wrapper generation

Avoid concurrent wrapper generation

---

internal/clientgen/typescript.go

Fixes https://github.com/encoredev/encore/issues/924

clientgen/typescript: add `?` when optional is added

---

pkg/pgproxy/pgproxy.go

This PR fixes an issue where pg clients would get stuck waiting for a server response after a proxied connection is terminated by the server

Gracefully close terminated pgproxy connections

---

docs/menu.cue
docs/tutorials/booking-system.md

A big tutorial counting in at 843 lines.
Left to do:
* I will create a project's starting-point branch
* Fill out the section "Sending confirmation emails using SendGrid"
* Maybe adding some tips and insights about the `time` package and how we are using it

Add booking system tutorial

---

docs/deploy/environments.md
docs/deploy/infra.md
docs/develop/app-structure.md
docs/introduction.md
docs/tutorials/booking-system.md

This PR clarifies the app structure documentation, improves the intro to Encore, and updates images for the infrastructure docs.

Docs: improve app structure docs and introduction to Encore

---

docs/primitives/services-and-apis-ts.md

Tag will be used as docs search filter

Add "ts" lang docs tag

---

pkg/encorebuild/compile/compile.go
pkg/rtconfgen/convert.go

- rtconfgen: handle missing graceful shutdown config
- encorebuild: use glibc 2.31 for rust binaries

build tweaks

---

runtimes/core/src/api/gateway/reverseproxy.rs
runtimes/core/src/api/schema/header.rs

- runtimes/core: fix header response serialization
- runtimes/core: append headers for gateway proxy

runtimes/core: fix response header serialization

---

docs/quick-start.mdx
docs/tutorials/rest-api.mdx

It doesn't work with highlight.js which we use.

docs: revert shell language tag

---

docs/index.mdx

Update docs image padding

---

cli/cmd/encore/app/create.go
cli/cmd/encore/app/create_form.go

* Fix minor bugs with create experience
* Allow declining creating an Encore account
* Remove beta label on TypeScript

cli: improve app create experience

---

cli/daemon/run/proc_groups.go
runtimes/core/src/api/endpoint.rs
tsparser/src/builder/templates/catalog/clients/endpoints_js.handlebars

- cli: propagate host header for api gateway
- tsparser: fix test codegen
- runtimes/core: treat invalid mac as no platform seal

minor ts fixes

---

cli/daemon/sqldb/docker/docker.go

Previously, running the `uptime` example Encore application using Podman that's correctly configured to emulate Docker would fail with the following error.
```sh
> encore run
✔ Building Encore application graph... Done!
✔ Analyzing service topology... Done!
❌ Creating PostgreSQL database cluster... Failed: failed to start cluster: check docker image: exit status 125
✔ Starting PubSub daemon... Done!
✔ Fetching application secrets... Done!
✔ Generating boilerplate code... Done!
✔ Compiling application source code... Done!
failed to start cluster: check docker image: exit status 125
```
This error did not provide enough information to understand what exactly failed without diving into the code. Luckily, I understood Podman well enough to check whether the code was using a short image name …

sqldb: support podman

---

cli/daemon/dash/ai/client.go
cli/daemon/dash/ai/manager.go
cli/daemon/dash/dash.go
cli/daemon/dash/server.go

Add logging and remove reuse of the graphql subscription handler to address bug where define endpoint sometimes hangs

ai: Fix hanging ai define endpoints call

---

runtimes/core/src/api/schema/path.rs
tsparser/src/parser/resources/apis/encoding.rs

tsparser: handle params in raw endpoints

---

runtimes/js/encore.dev/storage/sqldb/database.ts

In order to properly propagate any exception from
the query execution itself, we need to await the cursor, even though the result is thrown away. This is due to some peculiarities of how `tokio-postgres` behaves.
Thanks Olle Eriksson for the report!

runtimes/js: await cursor in db.exec

---

cli/internal/update/update.go
tsparser/src/legacymeta/schema.rs

cli: git fetch before brew update

---

tsparser/src/legacymeta/mod.rs
tsparser/src/parser/resources/infra/sqldb.rs
tsparser/src/parser/types/object.rs
tsparser/src/parser/usageparser/mod.rs

Sort schema migrations by number, and track more usage
types.

tsparser: improve database parsing

---

runtimes/go/appruntime/exported/config/parse.go
runtimes/go/appruntime/exported/config/parse_test.go

Adds support for gzipped runtime config env vars

runtimes/go: support gzipped runtime config

---

docs/how-to/insert-test-data-db.md

A small change, changing `webooks` to `webhooks` 🙂

docs: fix typo in `insert-test-data-db.md`

---

tsparser/src/bin/tsparser-encore.rs
tsparser/src/builder/codegen.rs
tsparser/src/builder/mod.rs
tsparser/src/builder/templates/entrypoints/combined/main.handlebars
tsparser/src/builder/templates/entrypoints/services/main.handlebars
tsparser/src/builder/transpiler.rs
tsparser/src/parser/resources/infra/pubsub_subscription.rs

Fixes an issue where they weren't initialized if they
were not otherwise being imported.

Import pubsub subscriptions in entrypoint

---

tsparser/src/bin/tsparser-encore.rs
tsparser/src/builder/transpiler.rs

fix: run cargo fmt

---

cli/internal/update/update.go

To properly update the brew repository we need to actually
pull the changes, not only fetch them.

cli: fix brew update

---

README.md

Since it is under the "Example: Hello World" section. Make is a similar to the TS example as possible so it is easier to compare.

Update go hello world example in readme

---

Cargo.lock
runtimes/core/src/sqldb/val.rs
tsparser/src/parser/types/typ.rs

Handle VARCHAR the same way we handle TEXT

runtime/core: handle varchar in psql

---

runtimes/core/src/api/gateway/mod.rs

Use pingoras error helpers for mapping `Option<T>` and `Result<T, E>` to pingora errors

Use pingoras error helpers

---

docs/deploy/webhooks.md
docs/develop/config.md

docs: fix typos

---

tsparser/src/builder/package_mgmt.rs

Tested locally with both a "normal" and a workspace project

tsparser: add support for pnpm

---

tsparser/src/builder/package_mgmt.rs

If no package manager is found in the apps `package.json`, search for a workspace `package.json` and parse it.

tsparser: Search for package manager in workspace

---

runtimes/js/encore.dev/package-lock.json

`npm audit fix` for building the js runtime

runtimes/js: bump braces

---

docs/community/contribute.md
docs/deploy/neon.md
docs/deploy/preview-environments.md

Hello
I found and fixed several spelling issues.
Br, Elias.

docs: fix spelling issues

---

runtimes/js/src/log.rs

Currently if logging fails, the log function throws an error, e.g if it cant deserialize a field. 
This PR changes so that we try to deserialize, and if that fails we use the type name instead, just to get some information (alternative we could filter those that fail, but imo that can cause some confusion if they just dont appear).

runtimes/ts: don't throw when logging fails

---

runtimes/core/src/pubsub/nsq/sub.rs

Thanks Olle Eriksson for the report!

runtimes/core: respect max retries for nsq

---

cli/daemon/run/tests.go

Without this I get a panic when running the e2e tests locally.

fix panic when running e2e-tests

---

docs/index.mdx

Corrected typo 'that' to 'than') in index.mdx

Corrected typo in index.mdx

---

cli/daemon/apps/apps.go
pkg/watcher/watcher.go

This refactors the file watching logic slightly. We've gotten reports
that sometimes file watching doesn't work as expected. It's not clear
exactly what the issue is, but possibly this refactoring will help.

cli: refactor file watching logic

---

runtimes/core/src/api/schema/encoding.rs

Handles handshake data with only path parameters

runtimes/core: handle handshake request with only path params

---

runtimes/core/src/lib.rs

To allow initialization such as https://github.com/encoredev/encore/issues/1388

runtimes/core: startup psql proxy early to allow initialization

---

e2e-tests/testdata/echo_client/js/client.js
e2e-tests/testdata/echo_client/ts/client.ts
internal/clientgen/javascript.go
internal/clientgen/testdata/goapp/expected_baseauth_javascript.js
internal/clientgen/testdata/goapp/expected_baseauth_typescript.ts
internal/clientgen/testdata/goapp/expected_javascript.js
internal/clientgen/testdata/goapp/expected_noauth_typescript.ts
internal/clientgen/testdata/goapp/expected_typescript.ts
internal/clientgen/testdata/tsapp/expected_golang.go
internal/clientgen/testdata/tsapp/expected_javascript.js
internal/clientgen/testdata/tsapp/expected_list_of_union_typescript.ts
internal/clientgen/testdata/tsapp/expected_stream_typescript.ts
internal/clientgen/testdata/tsapp/expected_typescript.ts
internal/clientgen/testdata/tsapp/input.ts
internal/clientgen/testdata/tsapp/tsconfig.json
internal/clientgen/typescript.go
internal/clientgen/utils.go
tsparser/src/legacymeta/mod.rs

clientgen: handle optional auth params

---

Cargo.lock
tsparser/Cargo.toml
tsparser/src/runtimeresolve/tsconfig.rs

Gives some relevant context of what file is causing the error

tsparser: improve errors around tsconfig parsing

---

tsparser/src/parser/parser.rs

Example:
```
Changes detected, recompiling...
error: Expression expected
--> /home/fredr/projects/encore-apps/teeeest/repro/repro.ts:28:17
|
28 |       const x = ;
|                 ^
```

tsparser: better syntax errors

---

tsparser/src/parser/resources/apis/api.rs
tsparser/src/parser/resources/apis/encoding.rs

Report errors with span so its easier to understand them

tsparser: better endpoint parser errors

---

tsparser/src/builder/codegen.rs

Fixes #1467. Thanks @zarubto4 for the report!

tsparser: fix codegen when file contains a period

---

docs/ts/primitives/streaming-apis.mdx

Add a small section about service to service streaming

docs: add information about stream service to service

---

internal/version/version.go

It's causing more problems than it solves.

internal/version: remove PATH from config hash

---

runtimes/core/src/api/gateway/mod.rs

Propagate the correct errors when no match in router

fix 404 when requesting a path that doesnt exist

---

cli/daemon/dash/dashproxy/dashproxy.go
go.mod
internal/httpcache/LICENSE.txt
internal/httpcache/README.md
internal/httpcache/diskcache/diskcache.go
internal/httpcache/diskcache/diskcache_test.go
internal/httpcache/httpcache.go
internal/httpcache/httpcache_test.go
internal/httpcache/test/test.go
internal/httpcache/test/test_test.go

- Vendor github.com/gregjones/httpcache
- dashproxy: improve cache handling

dashproxy caching

---

runtimes/go/rlog/rlog.go

runtimes/go: fix rlog ctx with repeated fields

---

docs/primitives/object-storage.md

docs: fix go object storage examples

---

runtimes/core/src/sqldb/val.rs
runtimes/js/src/pvalue.rs

- runtimes/core: fix enum row parsing
- runtimes/js: fix date decoding in ToNapiValue

misc tweaks

---

cli/cmd/encore/gen.go

Update unknown language error message

---

docs/ts/tutorials/uptime.md

tutorial: fix uptime test

---

docs/ts/develop/auth.md

Explain how to mock auth with vitest in encore.ts
Note: I couldn't find in 3mins how to generate the website to confirm the layout. It would be a nice addition to encourage contributions

Explain how to mock auth in encore.ts

---

runtimes/core/src/lib.rs
runtimes/core/src/log/consolewriter.rs
runtimes/core/src/log/writers.rs

fix new clippy lints

---

Cargo.lock

Includes:
- https://github.com/encoredev/swc/pull/1

tsparser: fix resolving of arrays in exports 

---

runtimes/core/src/api/static_assets.rs

so that we can distinguish in the match that it was the fallback that was called

fix: override not found status after fallback

---

runtimes/js/encore.dev/storage/sqldb/database.ts

Same as #1818 but for an acquired connection

runtimes/js: add new raw sql method for connection

---

internal/httpcache/README.md

https://github.com/syndtr/goleveldb/leveldb - dead link
https://github.com/syndtr/goleveldb/tree/master/leveldb - worked link

replace link README.md

---

Cargo.lock

See https://github.com/encoredev/swc/pull/2

tsparser: resolve conditional exports in the correct order

---

docs/ts/develop/orms/prisma.md

remove use of unregistered languages

---

tsparser/src/parser/types/object.rs

e.g `import * as foo from bar`

resolve namespaced import

---

go.mod
go.sum

bump zerolog

---

docs/ts/quick-start.mdx

Fixing a small possible typo in the doc.

fix: small possible typo in the doc

---

e2e-tests/testdata/testscript/ts_worker_pooling.txt

Just to make sure an app will start with this setting enabled

add simple e2e test that enabled worker pooling
